Doctor.create!([
  {name: "1", username: "2", password: nil, password_conformation: nil, specialization: nil, email: "k@k.k", encrypted_password: "$2a$10$m3d7CB9l4/xtdl2RiJsb0eP2FyzXFkS0CSr1Z.eZVydcBBwc5b9Z6", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: "2016-02-07 18:19:20", sign_in_count: 9, current_sign_in_at: "2016-03-07 05:24:51", last_sign_in_at: "2016-02-13 12:42:13", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "::1"}
])
ComplicationDiagnosis.create!([
  {name: "Диагноз0"},
  {name: "Диагноз1"},
  {name: "Диагноз2"},
  {name: "Диагноз3"},
  {name: "Диагноз4"},
  {name: "Диагноз5"},
  {name: "Диагноз6"},
  {name: "Диагноз7"},
  {name: "Диагноз8"},
  {name: "Диагноз9"}
])
ComplicationDiagnosisVisit.create!([
  {complication_diagnosis_id: nil, visit_id: 93, details: nil},
  {complication_diagnosis_id: nil, visit_id: 94, details: nil},
  {complication_diagnosis_id: nil, visit_id: 95, details: nil},
  {complication_diagnosis_id: nil, visit_id: 96, details: nil},
  {complication_diagnosis_id: nil, visit_id: 97, details: nil},
  {complication_diagnosis_id: nil, visit_id: 98, details: nil},
  {complication_diagnosis_id: nil, visit_id: 99, details: nil},
  {complication_diagnosis_id: nil, visit_id: 100, details: nil},
  {complication_diagnosis_id: nil, visit_id: 101, details: nil},
  {complication_diagnosis_id: nil, visit_id: 102, details: nil}
])
ConcomitantDiagnosis.create!([
  {name: "Диагноз0"},
  {name: "Диагноз1"},
  {name: "Диагноз2"},
  {name: "Диагноз3"},
  {name: "Диагноз4"},
  {name: "Диагноз5"},
  {name: "Диагноз6"},
  {name: "Диагноз7"},
  {name: "Диагноз8"},
  {name: "Диагноз9"}
])
ConcomitantDiagnosisVisit.create!([
  {concomitant_diagnosis_id: 1, visit_id: 1, details: "1"},
  {concomitant_diagnosis_id: 1, visit_id: 29, details: "1"},
  {concomitant_diagnosis_id: 1, visit_id: 29, details: "1"},
  {concomitant_diagnosis_id: 1, visit_id: 30, details: nil},
  {concomitant_diagnosis_id: nil, visit_id: 93, details: nil},
  {concomitant_diagnosis_id: nil, visit_id: 94, details: nil},
  {concomitant_diagnosis_id: nil, visit_id: 95, details: nil},
  {concomitant_diagnosis_id: nil, visit_id: 96, details: nil},
  {concomitant_diagnosis_id: nil, visit_id: 97, details: nil},
  {concomitant_diagnosis_id: nil, visit_id: 98, details: nil},
  {concomitant_diagnosis_id: nil, visit_id: 99, details: nil},
  {concomitant_diagnosis_id: nil, visit_id: 100, details: nil},
  {concomitant_diagnosis_id: nil, visit_id: 101, details: nil},
  {concomitant_diagnosis_id: nil, visit_id: 102, details: nil}
])
ConditionName.create!([
  {name: "Окраска", condition_type_id: 1, unique: false},
  {name: "Кожа", condition_type_id: 1, unique: true},
  {name: "Дополнительно", condition_type_id: 1, unique: false},
  {name: "Слизистая ротовой полости", condition_type_id: 2, unique: true},
  {name: "Коньюктива", condition_type_id: 3, unique: false},
  {name: "Поверхность", condition_type_id: 3, unique: true},
  {name: "Выражена", condition_type_id: 4, unique: true},
  {name: "Подкожные лимфатические узлы", condition_type_id: 5, unique: true},
  {name: "Тоны", condition_type_id: 6, unique: false},
  {name: "Шумы", condition_type_id: 6, unique: false},
  {name: "Артериальное давление", condition_type_id: 6, unique: true},
  {name: "ЧСС", condition_type_id: 6, unique: true},
  {name: "Одышка", condition_type_id: 7, unique: false},
  {name: "Частота дыхательных движений", condition_type_id: 7, unique: true},
  {name: "Перкуторный звук", condition_type_id: 7, unique: false},
  {name: "Границы лёгких", condition_type_id: 7, unique: false},
  {name: "В лёгких при аускультации дыхание", condition_type_id: 7, unique: false},
  {name: "Хрипы", condition_type_id: 7, unique: false},
  {name: "Мокрота", condition_type_id: 7, unique: true},
  {name: "Запах изо рта", condition_type_id: 8, unique: true},
  {name: "Язык", condition_type_id: 8, unique: false},
  {name: "Живот", condition_type_id: 8, unique: false},
  {name: "при пальпации", condition_type_id: 8, unique: false},
  {name: "Симптом раздражения брюшины ", condition_type_id: 8, unique: true},
  {name: "Печень", condition_type_id: 8, unique: false},
  {name: "Селезёнка", condition_type_id: 8, unique: false},
  {name: "Перистальтика", condition_type_id: 8, unique: false},
  {name: "Дефекация", condition_type_id: 8, unique: false},
  {name: "Симптом поколачивания по пояснице", condition_type_id: 9, unique: true},
  {name: "Мочеиспускание", condition_type_id: 9, unique: false}
])
ConditionType.create!([
  {name: "Кожные покровы"},
  {name: "Слизистая ротовой полости"},
  {name: "Конъюнктива"},
  {name: "Подкожно-жировая клетчатка"},
  {name: "Подкожные лимфатические узлы"},
  {name: "Сердечно-сосудистая система"},
  {name: "Дыхательная система"},
  {name: "Пищеварительная система"},
  {name: "Мочевыделительная система"}
])
ConditionValue.create!([
  {name: "бледна", condition_name_id: 1},
  {name: "бледно-розовая", condition_name_id: 1},
  {name: "мраморная", condition_name_id: 1},
  {name: "желтушная", condition_name_id: 1},
  {name: "покраснение", condition_name_id: 1},
  {name: "гиперемия", condition_name_id: 1},
  {name: "цианоз", condition_name_id: 1},
  {name: "акроцианоз", condition_name_id: 1},
  {name: "бронзовая", condition_name_id: 1},
  {name: "землистая", condition_name_id: 1},
  {name: "пигментация", condition_name_id: 1},
  {name: "влажная", condition_name_id: 2},
  {name: "сухая", condition_name_id: 2},
  {name: "cыпь", condition_name_id: 3},
  {name: "рубцы", condition_name_id: 3},
  {name: "стрии", condition_name_id: 3},
  {name: "расчёсы", condition_name_id: 3},
  {name: "ссадины", condition_name_id: 3},
  {name: "сосудистые звездочки", condition_name_id: 3},
  {name: "геморрагии", condition_name_id: 3},
  {name: "отёчность", condition_name_id: 3},
  {name: "розова", condition_name_id: 4},
  {name: "гиперемия", condition_name_id: 4},
  {name: "бледно-розовая", condition_name_id: 5},
  {name: "гиперемирована", condition_name_id: 5},
  {name: "желтушна", condition_name_id: 5},
  {name: "бело-фарфоровая", condition_name_id: 5},
  {name: "отёчна", condition_name_id: 5},
  {name: "гладкая", condition_name_id: 6},
  {name: "разрыхлена", condition_name_id: 6},
  {name: "избыточно", condition_name_id: 7},
  {name: "скудно", condition_name_id: 7},
  {name: "умеренно", condition_name_id: 7},
  {name: "не пальпируются", condition_name_id: 8},
  {name: "не увеличены", condition_name_id: 8},
  {name: "увеличены", condition_name_id: 8},
  {name: "ясные", condition_name_id: 10},
  {name: "громкие", condition_name_id: 10},
  {name: "приглушены", condition_name_id: 10},
  {name: "глухие", condition_name_id: 10},
  {name: "ритмичные", condition_name_id: 10},
  {name: "аритмичные", condition_name_id: 10},
  {name: "экстрасистолия", condition_name_id: 10},
  {name: "систолический", condition_name_id: 11},
  {name: "функциональный", condition_name_id: 11},
  {name: "органический", condition_name_id: 11},
  {name: "на верхушке", condition_name_id: 11},
  {name: "в т. Боткина", condition_name_id: 11},
  {name: "над грудиной", condition_name_id: 11},
  {name: "справа от грудины", condition_name_id: 11},
  {name: "отсутствует", condition_name_id: 14},
  {name: "инспираторная", condition_name_id: 14},
  {name: "экспираторная", condition_name_id: 14},
  {name: "возникает при", condition_name_id: 14},
  {name: "ясный лёгочный", condition_name_id: 16},
  {name: "притуплённый", condition_name_id: 16},
  {name: "укороченный", condition_name_id: 16},
  {name: "тимпанический", condition_name_id: 16},
  {name: "коробочный", condition_name_id: 16},
  {name: "металлический", condition_name_id: 16},
  {name: "одностороннее", condition_name_id: 17},
  {name: "двустороннее опущение", condition_name_id: 17},
  {name: "смещение вверх нижних границ ", condition_name_id: 17},
  {name: "везикулярное", condition_name_id: 18},
  {name: "жёсткое", condition_name_id: 18},
  {name: "ослаблено слева", condition_name_id: 18},
  {name: "ослаблено справа", condition_name_id: 18},
  {name: "ослаблено в верхних отделах", condition_name_id: 18},
  {name: "ослаблено в нижних отделах", condition_name_id: 18},
  {name: "ослаблено по передней поверхности", condition_name_id: 18},
  {name: "ослаблено по задней поверхности", condition_name_id: 18},
  {name: "ослаблено по боковой поверхности", condition_name_id: 18},
  {name: "отсутствуют", condition_name_id: 19},
  {name: "единичные", condition_name_id: 19},
  {name: "множественные", condition_name_id: 19},
  {name: "мелкопузырчатые", condition_name_id: 19},
  {name: "среднепузырчатые", condition_name_id: 19},
  {name: "крупнопузырчатые", condition_name_id: 19},
  {name: "сухие", condition_name_id: 19},
  {name: "влажные", condition_name_id: 19},
  {name: "свистящие", condition_name_id: 19},
  {name: "крепитирующие", condition_name_id: 19},
  {name: "застойного характера", condition_name_id: 19},
  {name: "слева", condition_name_id: 19},
  {name: "справа", condition_name_id: 19},
  {name: "по передней поверхности", condition_name_id: 19},
  {name: "по задней поверхности", condition_name_id: 19},
  {name: "по боковой поверхности", condition_name_id: 19},
  {name: "в верхних отделах", condition_name_id: 19},
  {name: "в средних отделах", condition_name_id: 19},
  {name: "в нижних отделах", condition_name_id: 19},
  {name: "влажный", condition_name_id: 22},
  {name: "сухой", condition_name_id: 22},
  {name: "чистый", condition_name_id: 22},
  {name: "обложен налётом ", condition_name_id: 22},
  {name: "увеличен за счёт п/жировой клетчатки", condition_name_id: 23},
  {name: "увеличен за счёт отёков", condition_name_id: 23},
  {name: "увеличен за счёт грыжевых выпячиваний", condition_name_id: 23},
  {name: "мягкий", condition_name_id: 24},
  {name: "безболезненный", condition_name_id: 24},
  {name: "болезненный", condition_name_id: 24},
  {name: "есть", condition_name_id: 25},
  {name: "нет", condition_name_id: 25},
  {name: "по краю рёберной дуги", condition_name_id: 26},
  {name: "увеличена", condition_name_id: 26},
  {name: "болезненная", condition_name_id: 26},
  {name: "плотная", condition_name_id: 26},
  {name: "мягкая", condition_name_id: 26},
  {name: "поверхность гладкая", condition_name_id: 26},
  {name: "поверхность бугристая", condition_name_id: 26},
  {name: "увеличена", condition_name_id: 27},
  {name: "болезненная", condition_name_id: 27},
  {name: "нарушена", condition_name_id: 28},
  {name: "не нарушена", condition_name_id: 28},
  {name: "безболезненная", condition_name_id: 29},
  {name: "болезненная", condition_name_id: 29},
  {name: "кал оформленный", condition_name_id: 29},
  {name: "кал жидкий", condition_name_id: 29},
  {name: "кал коричневого цвета", condition_name_id: 29},
  {name: "кал без примеси слизи и крови", condition_name_id: 29},
  {name: "отрицательный", condition_name_id: 31},
  {name: "положительный слева", condition_name_id: 31},
  {name: "положительный справа", condition_name_id: 31},
  {name: "положительный с обеих сторон", condition_name_id: 31},
  {name: "4-6 раз в сутки", condition_name_id: 32},
  {name: "безболезненное", condition_name_id: 32},
  {name: "болезненное", condition_name_id: 32},
  {name: "учащённое", condition_name_id: 32},
  {name: "редкое", condition_name_id: 32},
  {name: "никтурия", condition_name_id: 32},
  {name: "олигурия", condition_name_id: 32},
  {name: "анурия", condition_name_id: 32},
  {name: "моча светло-соломенного цвета", condition_name_id: 32}
])
ConditionVisit.create!([
  {visit_id: 82, condition_value_id: 44, details: ""},
  {visit_id: 82, condition_value_id: 45, details: ""},
  {visit_id: 82, condition_value_id: 46, details: ""},
  {visit_id: 82, condition_value_id: 47, details: ""},
  {visit_id: 83, condition_value_id: 44, details: ""},
  {visit_id: 83, condition_value_id: 45, details: ""},
  {visit_id: 83, condition_value_id: 46, details: ""},
  {visit_id: 83, condition_value_id: 47, details: ""},
  {visit_id: 84, condition_value_id: 44, details: ""},
  {visit_id: 84, condition_value_id: 45, details: ""},
  {visit_id: 84, condition_value_id: 46, details: ""},
  {visit_id: 84, condition_value_id: 47, details: ""},
  {visit_id: 85, condition_value_id: 44, details: ""},
  {visit_id: 85, condition_value_id: 45, details: ""},
  {visit_id: 85, condition_value_id: 46, details: ""},
  {visit_id: 85, condition_value_id: 47, details: ""},
  {visit_id: 86, condition_value_id: 44, details: ""},
  {visit_id: 86, condition_value_id: 45, details: ""},
  {visit_id: 86, condition_value_id: 46, details: ""},
  {visit_id: 86, condition_value_id: 47, details: ""},
  {visit_id: 87, condition_value_id: 44, details: ""},
  {visit_id: 87, condition_value_id: 45, details: ""},
  {visit_id: 87, condition_value_id: 46, details: ""},
  {visit_id: 87, condition_value_id: 47, details: ""},
  {visit_id: 88, condition_value_id: 44, details: ""},
  {visit_id: 88, condition_value_id: 45, details: ""},
  {visit_id: 88, condition_value_id: 46, details: ""},
  {visit_id: 88, condition_value_id: 47, details: ""}
])
ConstitutionOption.create!([
  {name: "Телосложение1"},
  {name: "Телосложение2"}
])
Consultation.create!([
  {visit_id: 81, specialist_id: 1, result: nil}
])
Diagnosis.create!([
  {name: "Диагноз0"},
  {name: "Диагноз1"},
  {name: "Диагноз2"},
  {name: "Диагноз3"},
  {name: "Диагноз4"},
  {name: "Диагноз5"},
  {name: "Диагноз6"},
  {name: "Диагноз7"},
  {name: "Диагноз8"},
  {name: "Диагноз9"}
])
EffleurageOption.create!([
  {name: "Отрицательный"},
  {name: "Положительный слева"},
  {name: "Положительный справа"},
  {name: "Положительный с обеих сторон"}
])
GeneralStateOption.create!([
  {name: "Удовлетворительное"},
  {name: "Относительно удовлетворительное"},
  {name: "Средней степени тяжести"},
  {name: "Тяжелое"}
])
Patient.create!([
  {name: nil, age: nil, gender: nil},
  {name: "2", age: 2, gender: "2"}
])
PosturalPoseOption.create!([
  {name: "Активное"},
  {name: "Пассивное"},
  {name: "Вынужденное"}
])
PrimaryDiagnosis.create!([
  {name: "Диагноз0"},
  {name: "Диагноз1"},
  {name: "Диагноз2"},
  {name: "Диагноз3"},
  {name: "Диагноз4"},
  {name: "Диагноз5"},
  {name: "Диагноз6"},
  {name: "Диагноз7"},
  {name: "Диагноз8"},
  {name: "Диагноз9"}
])
PrimaryDiagnosisVisit.create!([
  {visit_id: 29, primary_diagnosis_id: 1, details: nil},
  {visit_id: 29, primary_diagnosis_id: 1, details: nil},
  {visit_id: 29, primary_diagnosis_id: 1, details: nil},
  {visit_id: 29, primary_diagnosis_id: 1, details: nil},
  {visit_id: 101, primary_diagnosis_id: nil, details: nil},
  {visit_id: 102, primary_diagnosis_id: nil, details: nil}
])
Specialist.create!([
  {name: "Терапевт"},
  {name: "Физиотерапевт"}
])
Visit.create!([
  {from: "", complaints: "", anamnesis: "", allerg: "", general_state: "", diagnosis: "", doctor_id: 1, patient_id: 14, constitution_option_id: nil, general_state_option_id: nil, postural_pose_option_id: nil, subcutanious_fat_option_id: nil, effleurage_option_id: nil},
  {from: "", complaints: "", anamnesis: "", allerg: "", general_state: "", diagnosis: "", doctor_id: 1, patient_id: 14, constitution_option_id: 2, general_state_option_id: nil, postural_pose_option_id: nil, subcutanious_fat_option_id: nil, effleurage_option_id: nil},
  {from: "", complaints: "", anamnesis: "", allerg: "", general_state: nil, diagnosis: "", doctor_id: 1, patient_id: 14, constitution_option_id: 1, general_state_option_id: 4, postural_pose_option_id: 2, subcutanious_fat_option_id: nil, effleurage_option_id: 3},
  {from: "", complaints: "", anamnesis: "", allerg: "", general_state: nil, diagnosis: "", doctor_id: 1, patient_id: 14, constitution_option_id: 1, general_state_option_id: 1, postural_pose_option_id: 1, subcutanious_fat_option_id: nil, effleurage_option_id: 1},
  {from: "", complaints: "", anamnesis: "", allerg: "", general_state: nil, diagnosis: "", doctor_id: 1, patient_id: 14, constitution_option_id: 1, general_state_option_id: 1, postural_pose_option_id: 1, subcutanious_fat_option_id: nil, effleurage_option_id: 1},
  {from: "й", complaints: "", anamnesis: "", allerg: "", general_state: nil, diagnosis: "", doctor_id: 1, patient_id: 14, constitution_option_id: 1, general_state_option_id: 1, postural_pose_option_id: 1, subcutanious_fat_option_id: nil, effleurage_option_id: 1},
  {from: nil, complaints: nil, anamnesis: nil, allerg: nil, general_state: nil, diagnosis: nil, doctor_id: nil, patient_id: nil, constitution_option_id: nil, general_state_option_id: nil, postural_pose_option_id: nil, subcutanious_fat_option_id: nil, effleurage_option_id: nil},
  {from: nil, complaints: nil, anamnesis: nil, allerg: nil, general_state: nil, diagnosis: nil, doctor_id: nil, patient_id: nil, constitution_option_id: nil, general_state_option_id: nil, postural_pose_option_id: nil, subcutanious_fat_option_id: nil, effleurage_option_id: nil},
  {from: nil, complaints: nil, anamnesis: nil, allerg: nil, general_state: nil, diagnosis: nil, doctor_id: nil, patient_id: nil, constitution_option_id: nil, general_state_option_id: nil, postural_pose_option_id: nil, subcutanious_fat_option_id: nil, effleurage_option_id: nil},
  {from: nil, complaints: nil, anamnesis: nil, allerg: nil, general_state: nil, diagnosis: nil, doctor_id: nil, patient_id: nil, constitution_option_id: nil, general_state_option_id: nil, postural_pose_option_id: nil, subcutanious_fat_option_id: nil, effleurage_option_id: nil},
  {from: "ss", complaints: "", anamnesis: "", allerg: "", general_state: nil, diagnosis: "", doctor_id: 1, patient_id: 14, constitution_option_id: 1, general_state_option_id: 1, postural_pose_option_id: 1, subcutanious_fat_option_id: nil, effleurage_option_id: 1},
  {from: nil, complaints: nil, anamnesis: nil, allerg: nil, general_state: nil, diagnosis: nil, doctor_id: nil, patient_id: nil, constitution_option_id: nil, general_state_option_id: nil, postural_pose_option_id: nil, subcutanious_fat_option_id: nil, effleurage_option_id: nil},
  {from: nil, complaints: nil, anamnesis: nil, allerg: nil, general_state: nil, diagnosis: nil, doctor_id: nil, patient_id: nil, constitution_option_id: nil, general_state_option_id: nil, postural_pose_option_id: nil, subcutanious_fat_option_id: nil, effleurage_option_id: nil},
  {from: "", complaints: "", anamnesis: "", allerg: "", general_state: nil, diagnosis: "", doctor_id: 1, patient_id: 14, constitution_option_id: 1, general_state_option_id: 1, postural_pose_option_id: 1, subcutanious_fat_option_id: nil, effleurage_option_id: 1},
  {from: "", complaints: "", anamnesis: "", allerg: "", general_state: nil, diagnosis: "", doctor_id: 1, patient_id: 14, constitution_option_id: 1, general_state_option_id: 1, postural_pose_option_id: 1, subcutanious_fat_option_id: nil, effleurage_option_id: 1},
  {from: nil, complaints: nil, anamnesis: nil, allerg: nil, general_state: nil, diagnosis: nil, doctor_id: nil, patient_id: nil, constitution_option_id: nil, general_state_option_id: nil, postural_pose_option_id: nil, subcutanious_fat_option_id: nil, effleurage_option_id: nil},
  {from: "", complaints: "", anamnesis: "", allerg: "", general_state: nil, diagnosis: "", doctor_id: 1, patient_id: 14, constitution_option_id: 1, general_state_option_id: 1, postural_pose_option_id: 1, subcutanious_fat_option_id: nil, effleurage_option_id: 1},
  {from: nil, complaints: nil, anamnesis: nil, allerg: nil, general_state: nil, diagnosis: nil, doctor_id: nil, patient_id: nil, constitution_option_id: nil, general_state_option_id: nil, postural_pose_option_id: nil, subcutanious_fat_option_id: nil, effleurage_option_id: nil},
  {from: nil, complaints: nil, anamnesis: nil, allerg: nil, general_state: nil, diagnosis: nil, doctor_id: nil, patient_id: nil, constitution_option_id: nil, general_state_option_id: nil, postural_pose_option_id: nil, subcutanious_fat_option_id: nil, effleurage_option_id: nil},
  {from: nil, complaints: nil, anamnesis: nil, allerg: nil, general_state: nil, diagnosis: nil, doctor_id: nil, patient_id: nil, constitution_option_id: nil, general_state_option_id: nil, postural_pose_option_id: nil, subcutanious_fat_option_id: nil, effleurage_option_id: nil},
  {from: nil, complaints: nil, anamnesis: nil, allerg: nil, general_state: nil, diagnosis: nil, doctor_id: nil, patient_id: nil, constitution_option_id: nil, general_state_option_id: nil, postural_pose_option_id: nil, subcutanious_fat_option_id: nil, effleurage_option_id: nil},
  {from: nil, complaints: nil, anamnesis: nil, allerg: nil, general_state: nil, diagnosis: nil, doctor_id: nil, patient_id: nil, constitution_option_id: nil, general_state_option_id: nil, postural_pose_option_id: nil, subcutanious_fat_option_id: nil, effleurage_option_id: nil},
  {from: nil, complaints: nil, anamnesis: nil, allerg: nil, general_state: nil, diagnosis: nil, doctor_id: nil, patient_id: nil, constitution_option_id: nil, general_state_option_id: nil, postural_pose_option_id: nil, subcutanious_fat_option_id: nil, effleurage_option_id: nil},
  {from: nil, complaints: nil, anamnesis: nil, allerg: nil, general_state: nil, diagnosis: nil, doctor_id: nil, patient_id: nil, constitution_option_id: nil, general_state_option_id: nil, postural_pose_option_id: nil, subcutanious_fat_option_id: nil, effleurage_option_id: nil},
  {from: nil, complaints: nil, anamnesis: nil, allerg: nil, general_state: nil, diagnosis: nil, doctor_id: nil, patient_id: nil, constitution_option_id: nil, general_state_option_id: nil, postural_pose_option_id: nil, subcutanious_fat_option_id: nil, effleurage_option_id: nil},
  {from: nil, complaints: nil, anamnesis: nil, allerg: nil, general_state: nil, diagnosis: nil, doctor_id: nil, patient_id: nil, constitution_option_id: nil, general_state_option_id: nil, postural_pose_option_id: nil, subcutanious_fat_option_id: nil, effleurage_option_id: nil},
  {from: nil, complaints: nil, anamnesis: nil, allerg: nil, general_state: nil, diagnosis: nil, doctor_id: nil, patient_id: nil, constitution_option_id: nil, general_state_option_id: nil, postural_pose_option_id: nil, subcutanious_fat_option_id: nil, effleurage_option_id: nil},
  {from: nil, complaints: nil, anamnesis: nil, allerg: nil, general_state: nil, diagnosis: nil, doctor_id: nil, patient_id: nil, constitution_option_id: nil, general_state_option_id: nil, postural_pose_option_id: nil, subcutanious_fat_option_id: nil, effleurage_option_id: nil},
  {from: nil, complaints: nil, anamnesis: nil, allerg: nil, general_state: nil, diagnosis: nil, doctor_id: nil, patient_id: nil, constitution_option_id: nil, general_state_option_id: nil, postural_pose_option_id: nil, subcutanious_fat_option_id: nil, effleurage_option_id: nil},
  {from: nil, complaints: nil, anamnesis: nil, allerg: nil, general_state: nil, diagnosis: nil, doctor_id: nil, patient_id: nil, constitution_option_id: nil, general_state_option_id: nil, postural_pose_option_id: nil, subcutanious_fat_option_id: nil, effleurage_option_id: nil},
  {from: "", complaints: "", anamnesis: "", allerg: "", general_state: nil, diagnosis: "", doctor_id: 1, patient_id: 14, constitution_option_id: 1, general_state_option_id: 1, postural_pose_option_id: 1, subcutanious_fat_option_id: nil, effleurage_option_id: 1},
  {from: "", complaints: "", anamnesis: "", allerg: "", general_state: nil, diagnosis: "", doctor_id: 1, patient_id: 14, constitution_option_id: 1, general_state_option_id: 1, postural_pose_option_id: 1, subcutanious_fat_option_id: nil, effleurage_option_id: 1},
  {from: "", complaints: "", anamnesis: "", allerg: "", general_state: nil, diagnosis: "", doctor_id: 1, patient_id: 14, constitution_option_id: 1, general_state_option_id: 1, postural_pose_option_id: 1, subcutanious_fat_option_id: nil, effleurage_option_id: 1},
  {from: "", complaints: "", anamnesis: "", allerg: "", general_state: nil, diagnosis: "", doctor_id: 1, patient_id: 14, constitution_option_id: 1, general_state_option_id: 1, postural_pose_option_id: 1, subcutanious_fat_option_id: nil, effleurage_option_id: 1},
  {from: "", complaints: "", anamnesis: "", allerg: "", general_state: nil, diagnosis: "", doctor_id: 1, patient_id: 14, constitution_option_id: 1, general_state_option_id: 1, postural_pose_option_id: 1, subcutanious_fat_option_id: nil, effleurage_option_id: 1},
  {from: "", complaints: "", anamnesis: "", allerg: "", general_state: nil, diagnosis: "", doctor_id: 1, patient_id: 14, constitution_option_id: 1, general_state_option_id: 1, postural_pose_option_id: 1, subcutanious_fat_option_id: nil, effleurage_option_id: 1},
  {from: "", complaints: "", anamnesis: "", allerg: "", general_state: nil, diagnosis: "", doctor_id: 1, patient_id: 14, constitution_option_id: 1, general_state_option_id: 1, postural_pose_option_id: 1, subcutanious_fat_option_id: nil, effleurage_option_id: 1},
  {from: "", complaints: "", anamnesis: "", allerg: "", general_state: nil, diagnosis: "", doctor_id: 1, patient_id: 14, constitution_option_id: 1, general_state_option_id: 1, postural_pose_option_id: 1, subcutanious_fat_option_id: nil, effleurage_option_id: 1},
  {from: "", complaints: "", anamnesis: "", allerg: "", general_state: nil, diagnosis: "", doctor_id: 1, patient_id: 14, constitution_option_id: 1, general_state_option_id: 1, postural_pose_option_id: 1, subcutanious_fat_option_id: nil, effleurage_option_id: 1},
  {from: "", complaints: "", anamnesis: "", allerg: "", general_state: nil, diagnosis: "", doctor_id: 1, patient_id: 14, constitution_option_id: 1, general_state_option_id: 1, postural_pose_option_id: 1, subcutanious_fat_option_id: nil, effleurage_option_id: 1},
  {from: "", complaints: "", anamnesis: "", allerg: "", general_state: nil, diagnosis: "", doctor_id: 1, patient_id: 14, constitution_option_id: 1, general_state_option_id: 1, postural_pose_option_id: 1, subcutanious_fat_option_id: nil, effleurage_option_id: 1},
  {from: "", complaints: "", anamnesis: "", allerg: "", general_state: nil, diagnosis: "", doctor_id: 1, patient_id: 14, constitution_option_id: 1, general_state_option_id: 1, postural_pose_option_id: 1, subcutanious_fat_option_id: nil, effleurage_option_id: 1},
  {from: "", complaints: "", anamnesis: "", allerg: "", general_state: nil, diagnosis: "", doctor_id: 1, patient_id: 14, constitution_option_id: 1, general_state_option_id: 1, postural_pose_option_id: 1, subcutanious_fat_option_id: nil, effleurage_option_id: 1},
  {from: "", complaints: "", anamnesis: "", allerg: "", general_state: nil, diagnosis: "", doctor_id: 1, patient_id: 14, constitution_option_id: 1, general_state_option_id: 1, postural_pose_option_id: 1, subcutanious_fat_option_id: nil, effleurage_option_id: 1},
  {from: "", complaints: "", anamnesis: "", allerg: "", general_state: nil, diagnosis: "", doctor_id: 1, patient_id: 14, constitution_option_id: 1, general_state_option_id: 1, postural_pose_option_id: 1, subcutanious_fat_option_id: nil, effleurage_option_id: 1},
  {from: "", complaints: "", anamnesis: "", allerg: "", general_state: nil, diagnosis: "", doctor_id: 1, patient_id: 14, constitution_option_id: 1, general_state_option_id: 1, postural_pose_option_id: 1, subcutanious_fat_option_id: nil, effleurage_option_id: 1},
  {from: "", complaints: "", anamnesis: "", allerg: "", general_state: nil, diagnosis: "", doctor_id: 1, patient_id: 14, constitution_option_id: 1, general_state_option_id: 1, postural_pose_option_id: 1, subcutanious_fat_option_id: nil, effleurage_option_id: 1},
  {from: "", complaints: "", anamnesis: "", allerg: "", general_state: nil, diagnosis: "", doctor_id: 1, patient_id: 14, constitution_option_id: 1, general_state_option_id: 1, postural_pose_option_id: 1, subcutanious_fat_option_id: nil, effleurage_option_id: 1},
  {from: "", complaints: "", anamnesis: "", allerg: "", general_state: nil, diagnosis: "", doctor_id: 1, patient_id: 14, constitution_option_id: 1, general_state_option_id: 1, postural_pose_option_id: 1, subcutanious_fat_option_id: nil, effleurage_option_id: 1},
  {from: "", complaints: "", anamnesis: "", allerg: "", general_state: nil, diagnosis: "", doctor_id: 1, patient_id: 14, constitution_option_id: 1, general_state_option_id: 1, postural_pose_option_id: 1, subcutanious_fat_option_id: nil, effleurage_option_id: 1},
  {from: "", complaints: "", anamnesis: "", allerg: "", general_state: nil, diagnosis: "", doctor_id: 1, patient_id: 14, constitution_option_id: 1, general_state_option_id: 1, postural_pose_option_id: 1, subcutanious_fat_option_id: nil, effleurage_option_id: 1},
  {from: "", complaints: "", anamnesis: "", allerg: "", general_state: nil, diagnosis: "", doctor_id: 1, patient_id: 14, constitution_option_id: 1, general_state_option_id: 1, postural_pose_option_id: 1, subcutanious_fat_option_id: nil, effleurage_option_id: 1},
  {from: "", complaints: "", anamnesis: "", allerg: "", general_state: nil, diagnosis: "", doctor_id: 1, patient_id: 14, constitution_option_id: 1, general_state_option_id: 1, postural_pose_option_id: 1, subcutanious_fat_option_id: nil, effleurage_option_id: 1},
  {from: "", complaints: "", anamnesis: "", allerg: "", general_state: nil, diagnosis: "", doctor_id: 1, patient_id: 14, constitution_option_id: 1, general_state_option_id: 1, postural_pose_option_id: 1, subcutanious_fat_option_id: nil, effleurage_option_id: 1},
  {from: "", complaints: "", anamnesis: "", allerg: "", general_state: nil, diagnosis: "", doctor_id: 1, patient_id: 14, constitution_option_id: 1, general_state_option_id: 1, postural_pose_option_id: 1, subcutanious_fat_option_id: nil, effleurage_option_id: 1},
  {from: "", complaints: "", anamnesis: "", allerg: "", general_state: nil, diagnosis: "", doctor_id: 1, patient_id: 14, constitution_option_id: 1, general_state_option_id: 1, postural_pose_option_id: 1, subcutanious_fat_option_id: nil, effleurage_option_id: 1},
  {from: "", complaints: "", anamnesis: "", allerg: "", general_state: nil, diagnosis: "", doctor_id: 1, patient_id: 14, constitution_option_id: 1, general_state_option_id: 1, postural_pose_option_id: 1, subcutanious_fat_option_id: nil, effleurage_option_id: 1},
  {from: "", complaints: "", anamnesis: "", allerg: "", general_state: nil, diagnosis: "", doctor_id: 1, patient_id: 14, constitution_option_id: 1, general_state_option_id: 1, postural_pose_option_id: 1, subcutanious_fat_option_id: nil, effleurage_option_id: 1},
  {from: "", complaints: "", anamnesis: "", allerg: "", general_state: nil, diagnosis: "", doctor_id: 1, patient_id: 14, constitution_option_id: 1, general_state_option_id: 1, postural_pose_option_id: 1, subcutanious_fat_option_id: nil, effleurage_option_id: 1},
  {from: "", complaints: "", anamnesis: "", allerg: "", general_state: nil, diagnosis: "", doctor_id: 1, patient_id: 14, constitution_option_id: 1, general_state_option_id: 1, postural_pose_option_id: 1, subcutanious_fat_option_id: nil, effleurage_option_id: 1},
  {from: "", complaints: "", anamnesis: "", allerg: "", general_state: nil, diagnosis: "", doctor_id: 1, patient_id: 14, constitution_option_id: 1, general_state_option_id: 1, postural_pose_option_id: 1, subcutanious_fat_option_id: nil, effleurage_option_id: 1},
  {from: "", complaints: "", anamnesis: "", allerg: "", general_state: nil, diagnosis: "", doctor_id: 1, patient_id: 14, constitution_option_id: 1, general_state_option_id: 1, postural_pose_option_id: 1, subcutanious_fat_option_id: nil, effleurage_option_id: 1},
  {from: "", complaints: "", anamnesis: "", allerg: "", general_state: nil, diagnosis: "", doctor_id: 1, patient_id: 14, constitution_option_id: 1, general_state_option_id: 1, postural_pose_option_id: 1, subcutanious_fat_option_id: nil, effleurage_option_id: 1},
  {from: "", complaints: "", anamnesis: "", allerg: "", general_state: nil, diagnosis: "", doctor_id: 1, patient_id: 14, constitution_option_id: 1, general_state_option_id: 1, postural_pose_option_id: 1, subcutanious_fat_option_id: nil, effleurage_option_id: 1},
  {from: "", complaints: "", anamnesis: "", allerg: "", general_state: nil, diagnosis: "", doctor_id: 1, patient_id: 14, constitution_option_id: 1, general_state_option_id: 1, postural_pose_option_id: 1, subcutanious_fat_option_id: nil, effleurage_option_id: 1},
  {from: "", complaints: "", anamnesis: "", allerg: "", general_state: nil, diagnosis: "", doctor_id: 1, patient_id: 14, constitution_option_id: 1, general_state_option_id: 1, postural_pose_option_id: 1, subcutanious_fat_option_id: nil, effleurage_option_id: 1},
  {from: "", complaints: "", anamnesis: "", allerg: "", general_state: nil, diagnosis: "", doctor_id: 1, patient_id: 14, constitution_option_id: 1, general_state_option_id: 1, postural_pose_option_id: 1, subcutanious_fat_option_id: nil, effleurage_option_id: 1},
  {from: "", complaints: "", anamnesis: "", allerg: "", general_state: nil, diagnosis: "", doctor_id: 1, patient_id: 14, constitution_option_id: 1, general_state_option_id: 1, postural_pose_option_id: 1, subcutanious_fat_option_id: nil, effleurage_option_id: 1},
  {from: "", complaints: "", anamnesis: "", allerg: "", general_state: nil, diagnosis: "", doctor_id: 1, patient_id: 14, constitution_option_id: 1, general_state_option_id: 1, postural_pose_option_id: 1, subcutanious_fat_option_id: nil, effleurage_option_id: 1},
  {from: "", complaints: "", anamnesis: "", allerg: "", general_state: nil, diagnosis: "", doctor_id: 1, patient_id: 14, constitution_option_id: 1, general_state_option_id: 1, postural_pose_option_id: 1, subcutanious_fat_option_id: nil, effleurage_option_id: 1},
  {from: "", complaints: "", anamnesis: "", allerg: "", general_state: nil, diagnosis: "", doctor_id: 1, patient_id: 14, constitution_option_id: 1, general_state_option_id: 1, postural_pose_option_id: 1, subcutanious_fat_option_id: nil, effleurage_option_id: 1},
  {from: "", complaints: "", anamnesis: "", allerg: "", general_state: nil, diagnosis: "", doctor_id: 1, patient_id: 14, constitution_option_id: 1, general_state_option_id: 1, postural_pose_option_id: 1, subcutanious_fat_option_id: nil, effleurage_option_id: 1},
  {from: "", complaints: "", anamnesis: "", allerg: "", general_state: nil, diagnosis: "", doctor_id: 1, patient_id: 14, constitution_option_id: 1, general_state_option_id: 1, postural_pose_option_id: 1, subcutanious_fat_option_id: nil, effleurage_option_id: 1},
  {from: "", complaints: "", anamnesis: "", allerg: "", general_state: nil, diagnosis: "", doctor_id: 1, patient_id: 14, constitution_option_id: 1, general_state_option_id: 1, postural_pose_option_id: 1, subcutanious_fat_option_id: nil, effleurage_option_id: 1}
])
