# ActsAsTaggableOn::Tag.create!([
#   {name: "Паспорт", taggings_count: 1}
# ])
# Doctor.create!([
#   {name: nil, username: nil, password: nil, password_conformation: nil, specialization: nil, email: "", encrypted_password: "$2a$10$UUYM/1hd3Zr4eEflzS9Fs.NLxGOQcQOBzLJc5ILK/vIS0qOV0gQAW", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2016-05-20 12:14:33", last_sign_in_at: "2016-05-20 12:14:33", current_sign_in_ip: "::1", last_sign_in_ip: "::1", company_name: "Одуванчик", company_address: "Ленина, 5", company_code: "1111111111111", documentation_code: nil, roles_mask: nil}
# ])
# ReportItem.create!([
#   {name: "Отчет", quantity: -1, percentage: nil, parent_id: nil, horizontal_counter: 0, ancestry: nil, full_name: "Отчет"},
#   {name: "Всего", quantity: 54, percentage: nil, parent_id: nil, horizontal_counter: 0, ancestry: "1", full_name: "Всего"}
# ])

# AnamnesisType.create!([
#   {name: "Перенесенные заболевания"},
#   {name: "Наследственность"},
#   {name: "Гинекологический анамнез"},
#   {name: "Аллергоанамнез"},
#   {name: "Операции, травмы"},
#   {name: "Вредные привычки"},
#   {name: "Жил-был. условия"},
#   {name: "Питание"},
#   {name: "Перенесенные заболевания"},
#   {name: "Наследственность"},
#   {name: "Гинекологический анамнез"},
#   {name: "Аллергоанамнез"},
#   {name: "Операции, травмы"},
#   {name: "Вредные привычки"},
#   {name: "Жил-был. условия"},
#   {name: "Питание"}
# ])

# AnamnesisName.create!([
#   {name: "Туберкулез", anamnesis_type_id: 1, unique: false},
#   {name: "Вен. заболевания", anamnesis_type_id: 1, unique: true},
#   {name: "Вирусный гепатит", anamnesis_type_id: 1, unique: false},
#   {name: "Наследственность", anamnesis_type_id: 2, unique: true},
#   {name: "Mensis", anamnesis_type_id: 3, unique: false},
#   {name: "Аллергоанамнез", anamnesis_type_id: 4, unique: true},
#   {name: "Операции, травмы", anamnesis_type_id: 5, unique: true},
#   {name: "Алкоголь", anamnesis_type_id: 6, unique: true},
#   {name: "Курение", anamnesis_type_id: 6, unique: true},
#   {name: "Наркотики", anamnesis_type_id: 6, unique: true},
#   {name: "Жил-был. условия", anamnesis_type_id: 7, unique: false},
#   {name: "Питание", anamnesis_type_id: 8, unique: false},
#   {name: "Туберкулез", anamnesis_type_id: 1, unique: false},
#   {name: "Вен. заболевания", anamnesis_type_id: 1, unique: true},
#   {name: "Вирусный гепатит", anamnesis_type_id: 1, unique: false},
#   {name: "Наследственность", anamnesis_type_id: 2, unique: true},
#   {name: "Mensis", anamnesis_type_id: 3, unique: false},
#   {name: "Аллергоанамнез", anamnesis_type_id: 4, unique: true},
#   {name: "Операции, травмы", anamnesis_type_id: 5, unique: true},
#   {name: "Алкоголь", anamnesis_type_id: 6, unique: true},
#   {name: "Курение", anamnesis_type_id: 6, unique: true},
#   {name: "Наркотики", anamnesis_type_id: 6, unique: true},
#   {name: "Жил-был. условия", anamnesis_type_id: 7, unique: false},
#   {name: "Питание", anamnesis_type_id: 8, unique: false}
# ])

# AnamnesisValue.create!([
#   {name: "нет", anamnesis_name_id: 1},
#   {name: "да", anamnesis_name_id: 1},
#   {name: "нет", anamnesis_name_id: 2},
#   {name: "да", anamnesis_name_id: 2},
#   {name: "нет", anamnesis_name_id: 3},
#   {name: "да", anamnesis_name_id: 3},
#   {name: "нерегулярные", anamnesis_name_id: 5},
#   {name: "регулярные", anamnesis_name_id: 5},
#   {name: "болезненные", anamnesis_name_id: 5},
#   {name: "безболезненные", anamnesis_name_id: 5},
#   {name: "обильные", anamnesis_name_id: 5},
#   {name: "необильные", anamnesis_name_id: 5},
#   {name: "спокоен", anamnesis_name_id: 5},
#   {name: "отягощен", anamnesis_name_id: 5},
#   {name: "нет", anamnesis_name_id: 6},
#   {name: "да", anamnesis_name_id: 6},
#   {name: "нет", anamnesis_name_id: 7},
#   {name: "да", anamnesis_name_id: 7},
#   {name: "нет", anamnesis_name_id: 8},
#   {name: "да", anamnesis_name_id: 8},
#   {name: "нет", anamnesis_name_id: 9},
#   {name: "да", anamnesis_name_id: 9},
#   {name: "удовлетворительное", anamnesis_name_id: 10},
#   {name: "неудовлетворительное", anamnesis_name_id: 10},
#   {name: "достаточное", anamnesis_name_id: 11},
#   {name: "недостаточное", anamnesis_name_id: 11}
# ])
# ComplicationDiagnosis.create!([
#   {name: "Диагноз0"},
#   {name: "Диагноз1"},
#   {name: "Диагноз2"},
#   {name: "Диагноз3"},
#   {name: "Диагноз4"},
#   {name: "Диагноз5"},
#   {name: "Диагноз6"},
#   {name: "Диагноз7"},
#   {name: "Диагноз8"},
#   {name: "Диагноз9"},
#   {name: "Диагноз0"},
#   {name: "Диагноз1"},
#   {name: "Диагноз2"},
#   {name: "Диагноз3"},
#   {name: "Диагноз4"},
#   {name: "Диагноз5"},
#   {name: "Диагноз6"},
#   {name: "Диагноз7"},
#   {name: "Диагноз8"},
#   {name: "Диагноз9"},
#   {name: "Диагноз0"},
#   {name: "Диагноз1"},
#   {name: "Диагноз2"},
#   {name: "Диагноз3"},
#   {name: "Диагноз4"},
#   {name: "Диагноз5"},
#   {name: "Диагноз6"},
#   {name: "Диагноз7"},
#   {name: "Диагноз8"},
#   {name: "Диагноз9"},
#   {name: "Диагноз0"},
#   {name: "Диагноз1"},
#   {name: "Диагноз2"},
#   {name: "Диагноз3"},
#   {name: "Диагноз4"},
#   {name: "Диагноз5"},
#   {name: "Диагноз6"},
#   {name: "Диагноз7"},
#   {name: "Диагноз8"},
#   {name: "Диагноз9"},
#   {name: "Диагноз0"},
#   {name: "Диагноз1"},
#   {name: "Диагноз2"},
#   {name: "Диагноз3"},
#   {name: "Диагноз4"},
#   {name: "Диагноз5"},
#   {name: "Диагноз6"},
#   {name: "Диагноз7"},
#   {name: "Диагноз8"},
#   {name: "Диагноз9"}
# ])
# ComplicationDiagnosisVisit.create!([
#   {complication_diagnosis_id: nil, visit_id: 93, details: nil},
#   {complication_diagnosis_id: nil, visit_id: 94, details: nil},
#   {complication_diagnosis_id: nil, visit_id: 95, details: nil},
#   {complication_diagnosis_id: nil, visit_id: 96, details: nil},
#   {complication_diagnosis_id: nil, visit_id: 97, details: nil},
#   {complication_diagnosis_id: nil, visit_id: 98, details: nil},
#   {complication_diagnosis_id: nil, visit_id: 99, details: nil},
#   {complication_diagnosis_id: nil, visit_id: 100, details: nil},
#   {complication_diagnosis_id: nil, visit_id: 101, details: nil},
#   {complication_diagnosis_id: nil, visit_id: 102, details: nil}
# ])
# ConcomitantDiagnosis.create!([
#   {name: "Диагноз0"},
#   {name: "Диагноз1"},
#   {name: "Диагноз2"},
#   {name: "Диагноз3"},
#   {name: "Диагноз4"},
#   {name: "Диагноз5"},
#   {name: "Диагноз6"},
#   {name: "Диагноз7"},
#   {name: "Диагноз8"},
#   {name: "Диагноз9"},
#   {name: "Диагноз0"},
#   {name: "Диагноз1"},
#   {name: "Диагноз2"},
#   {name: "Диагноз3"},
#   {name: "Диагноз4"},
#   {name: "Диагноз5"},
#   {name: "Диагноз6"},
#   {name: "Диагноз7"},
#   {name: "Диагноз8"},
#   {name: "Диагноз9"},
#   {name: "Диагноз0"},
#   {name: "Диагноз1"},
#   {name: "Диагноз2"},
#   {name: "Диагноз3"},
#   {name: "Диагноз4"},
#   {name: "Диагноз5"},
#   {name: "Диагноз6"},
#   {name: "Диагноз7"},
#   {name: "Диагноз8"},
#   {name: "Диагноз9"},
#   {name: "Диагноз0"},
#   {name: "Диагноз1"},
#   {name: "Диагноз2"},
#   {name: "Диагноз3"},
#   {name: "Диагноз4"},
#   {name: "Диагноз5"},
#   {name: "Диагноз6"},
#   {name: "Диагноз7"},
#   {name: "Диагноз8"},
#   {name: "Диагноз9"},
#   {name: "Диагноз0"},
#   {name: "Диагноз1"},
#   {name: "Диагноз2"},
#   {name: "Диагноз3"},
#   {name: "Диагноз4"},
#   {name: "Диагноз5"},
#   {name: "Диагноз6"},
#   {name: "Диагноз7"},
#   {name: "Диагноз8"},
#   {name: "Диагноз9"}
# ])
# ConcomitantDiagnosisVisit.create!([
#   {concomitant_diagnosis_id: 1, visit_id: 1, details: "1"},
#   {concomitant_diagnosis_id: 1, visit_id: 29, details: "1"},
#   {concomitant_diagnosis_id: 1, visit_id: 29, details: "1"},
#   {concomitant_diagnosis_id: 1, visit_id: 30, details: nil},
#   {concomitant_diagnosis_id: nil, visit_id: 93, details: nil},
#   {concomitant_diagnosis_id: nil, visit_id: 94, details: nil},
#   {concomitant_diagnosis_id: nil, visit_id: 95, details: nil},
#   {concomitant_diagnosis_id: nil, visit_id: 96, details: nil},
#   {concomitant_diagnosis_id: nil, visit_id: 97, details: nil},
#   {concomitant_diagnosis_id: nil, visit_id: 98, details: nil},
#   {concomitant_diagnosis_id: nil, visit_id: 99, details: nil},
#   {concomitant_diagnosis_id: nil, visit_id: 100, details: nil},
#   {concomitant_diagnosis_id: nil, visit_id: 101, details: nil},
#   {concomitant_diagnosis_id: nil, visit_id: 102, details: nil}
# ])

# ConditionType.create!([
#   {name: "Кожные покровы"},
#   {name: "Слизистая ротовой полости"},
#   {name: "Конъюнктива"},
#   {name: "Подкожно-жировая клетчатка"},
#   {name: "Подкожные лимфатические узлы"},
#   {name: "Сердечно-сосудистая система"},
#   {name: "Дыхательная система"},
#   {name: "Пищеварительная система"},
#   {name: "Мочевыделительная система"}
# ])

# ConditionName.create!([
#   {name: "Окраска", condition_type_id: 1, unique: false},
#   {name: "Кожа", condition_type_id: 1, unique: true},
#   {name: "Дополнительно", condition_type_id: 1, unique: false},
#   {name: "Слизистая ротовой полости", condition_type_id: 2, unique: true},
#   {name: "Коньюктива", condition_type_id: 3, unique: false},
#   {name: "Поверхность", condition_type_id: 3, unique: true},
#   {name: "Выражена", condition_type_id: 4, unique: true},
#   {name: "Подкожные лимфатические узлы", condition_type_id: 5, unique: true},
#   {name: "Тоны", condition_type_id: 6, unique: false},
#   {name: "Шумы", condition_type_id: 6, unique: false},
#   {name: "Артериальное давление", condition_type_id: 6, unique: true},
#   {name: "ЧСС", condition_type_id: 6, unique: true},
#   {name: "Одышка", condition_type_id: 7, unique: false},
#   {name: "Частота дыхательных движений", condition_type_id: 7, unique: true},
#   {name: "Перкуторный звук", condition_type_id: 7, unique: false},
#   {name: "Границы лёгких", condition_type_id: 7, unique: false},
#   {name: "В лёгких при аускультации дыхание", condition_type_id: 7, unique: false},
#   {name: "Хрипы", condition_type_id: 7, unique: false},
#   {name: "Мокрота", condition_type_id: 7, unique: true},
#   {name: "Запах изо рта", condition_type_id: 8, unique: true},
#   {name: "Язык", condition_type_id: 8, unique: false},
#   {name: "Живот", condition_type_id: 8, unique: false},
#   {name: "при пальпации", condition_type_id: 8, unique: false},
#   {name: "Симптом раздражения брюшины ", condition_type_id: 8, unique: true},
#   {name: "Печень", condition_type_id: 8, unique: false},
#   {name: "Селезёнка", condition_type_id: 8, unique: false},
#   {name: "Перистальтика", condition_type_id: 8, unique: false},
#   {name: "Дефекация", condition_type_id: 8, unique: false},
#   {name: "Симптом поколачивания по пояснице", condition_type_id: 9, unique: true},
#   {name: "Мочеиспускание", condition_type_id: 9, unique: false}
# ])

# ConditionValue.create!([
#   {name: "бледна", condition_name_id: 1},
#   {name: "бледно-розовая", condition_name_id: 1},
#   {name: "мраморная", condition_name_id: 1},
#   {name: "желтушная", condition_name_id: 1},
#   {name: "покраснение", condition_name_id: 1},
#   {name: "гиперемия", condition_name_id: 1},
#   {name: "цианоз", condition_name_id: 1},
#   {name: "акроцианоз", condition_name_id: 1},
#   {name: "бронзовая", condition_name_id: 1},
#   {name: "землистая", condition_name_id: 1},
#   {name: "пигментация", condition_name_id: 1},
#   {name: "влажная", condition_name_id: 2},
#   {name: "сухая", condition_name_id: 2},
#   {name: "cыпь", condition_name_id: 3},
#   {name: "рубцы", condition_name_id: 3},
#   {name: "стрии", condition_name_id: 3},
#   {name: "расчёсы", condition_name_id: 3},
#   {name: "ссадины", condition_name_id: 3},
#   {name: "сосудистые звездочки", condition_name_id: 3},
#   {name: "геморрагии", condition_name_id: 3},
#   {name: "отёчность", condition_name_id: 3},
#   {name: "розова", condition_name_id: 4},
#   {name: "гиперемия", condition_name_id: 4},
#   {name: "бледно-розовая", condition_name_id: 5},
#   {name: "гиперемирована", condition_name_id: 5},
#   {name: "желтушна", condition_name_id: 5},
#   {name: "бело-фарфоровая", condition_name_id: 5},
#   {name: "отёчна", condition_name_id: 5},
#   {name: "гладкая", condition_name_id: 6},
#   {name: "разрыхлена", condition_name_id: 6},
#   {name: "избыточно", condition_name_id: 7},
#   {name: "скудно", condition_name_id: 7},
#   {name: "умеренно", condition_name_id: 7},
#   {name: "не пальпируются", condition_name_id: 8},
#   {name: "не увеличены", condition_name_id: 8},
#   {name: "увеличены", condition_name_id: 8},
#   {name: "ясные", condition_name_id: 10},
#   {name: "громкие", condition_name_id: 10},
#   {name: "приглушены", condition_name_id: 10},
#   {name: "глухие", condition_name_id: 10},
#   {name: "ритмичные", condition_name_id: 10},
#   {name: "аритмичные", condition_name_id: 10},
#   {name: "экстрасистолия", condition_name_id: 10},
#   {name: "систолический", condition_name_id: 11},
#   {name: "функциональный", condition_name_id: 11},
#   {name: "органический", condition_name_id: 11},
#   {name: "на верхушке", condition_name_id: 11},
#   {name: "в т. Боткина", condition_name_id: 11},
#   {name: "над грудиной", condition_name_id: 11},
#   {name: "справа от грудины", condition_name_id: 11},
#   {name: "отсутствует", condition_name_id: 14},
#   {name: "инспираторная", condition_name_id: 14},
#   {name: "экспираторная", condition_name_id: 14},
#   {name: "возникает при", condition_name_id: 14},
#   {name: "ясный лёгочный", condition_name_id: 16},
#   {name: "притуплённый", condition_name_id: 16},
#   {name: "укороченный", condition_name_id: 16},
#   {name: "тимпанический", condition_name_id: 16},
#   {name: "коробочный", condition_name_id: 16},
#   {name: "металлический", condition_name_id: 16},
#   {name: "одностороннее", condition_name_id: 17},
#   {name: "двустороннее опущение", condition_name_id: 17},
#   {name: "смещение вверх нижних границ ", condition_name_id: 17},
#   {name: "везикулярное", condition_name_id: 18},
#   {name: "жёсткое", condition_name_id: 18},
#   {name: "ослаблено слева", condition_name_id: 18},
#   {name: "ослаблено справа", condition_name_id: 18},
#   {name: "ослаблено в верхних отделах", condition_name_id: 18},
#   {name: "ослаблено в нижних отделах", condition_name_id: 18},
#   {name: "ослаблено по передней поверхности", condition_name_id: 18},
#   {name: "ослаблено по задней поверхности", condition_name_id: 18},
#   {name: "ослаблено по боковой поверхности", condition_name_id: 18},
#   {name: "отсутствуют", condition_name_id: 19},
#   {name: "единичные", condition_name_id: 19},
#   {name: "множественные", condition_name_id: 19},
#   {name: "мелкопузырчатые", condition_name_id: 19},
#   {name: "среднепузырчатые", condition_name_id: 19},
#   {name: "крупнопузырчатые", condition_name_id: 19},
#   {name: "сухие", condition_name_id: 19},
#   {name: "влажные", condition_name_id: 19},
#   {name: "свистящие", condition_name_id: 19},
#   {name: "крепитирующие", condition_name_id: 19},
#   {name: "застойного характера", condition_name_id: 19},
#   {name: "слева", condition_name_id: 19},
#   {name: "справа", condition_name_id: 19},
#   {name: "по передней поверхности", condition_name_id: 19},
#   {name: "по задней поверхности", condition_name_id: 19},
#   {name: "по боковой поверхности", condition_name_id: 19},
#   {name: "в верхних отделах", condition_name_id: 19},
#   {name: "в средних отделах", condition_name_id: 19},
#   {name: "в нижних отделах", condition_name_id: 19},
#   {name: "влажный", condition_name_id: 22},
#   {name: "сухой", condition_name_id: 22},
#   {name: "чистый", condition_name_id: 22},
#   {name: "обложен налётом ", condition_name_id: 22},
#   {name: "увеличен за счёт п/жировой клетчатки", condition_name_id: 23},
#   {name: "увеличен за счёт отёков", condition_name_id: 23},
#   {name: "увеличен за счёт грыжевых выпячиваний", condition_name_id: 23},
#   {name: "мягкий", condition_name_id: 24},
#   {name: "безболезненный", condition_name_id: 24},
#   {name: "болезненный", condition_name_id: 24},
#   {name: "есть", condition_name_id: 25},
#   {name: "нет", condition_name_id: 25},
#   {name: "по краю рёберной дуги", condition_name_id: 26},
#   {name: "увеличена", condition_name_id: 26},
#   {name: "болезненная", condition_name_id: 26},
#   {name: "плотная", condition_name_id: 26},
#   {name: "мягкая", condition_name_id: 26},
#   {name: "поверхность гладкая", condition_name_id: 26},
#   {name: "поверхность бугристая", condition_name_id: 26},
#   {name: "увеличена", condition_name_id: 27},
#   {name: "болезненная", condition_name_id: 27},
#   {name: "нарушена", condition_name_id: 28},
#   {name: "не нарушена", condition_name_id: 28},
#   {name: "безболезненная", condition_name_id: 29},
#   {name: "болезненная", condition_name_id: 29},
#   {name: "кал оформленный", condition_name_id: 29},
#   {name: "кал жидкий", condition_name_id: 29},
#   {name: "кал коричневого цвета", condition_name_id: 29},
#   {name: "кал без примеси слизи и крови", condition_name_id: 29},
#   {name: "бледная", condition_name_id: 1},
#   {name: "бледно-розовая", condition_name_id: 1},
#   {name: "мраморная", condition_name_id: 1},
#   {name: "желтушная", condition_name_id: 1},
#   {name: "покраснение", condition_name_id: 1},
#   {name: "гиперемия", condition_name_id: 1},
#   {name: "цианоз", condition_name_id: 1},
#   {name: "акроцианоз", condition_name_id: 1},
#   {name: "бронзовая", condition_name_id: 1},
#   {name: "землистая", condition_name_id: 1},
#   {name: "пигментация", condition_name_id: 1},
#   {name: "влажная", condition_name_id: 2},
#   {name: "сухая", condition_name_id: 2},
#   {name: "cыпь", condition_name_id: 3},
#   {name: "рубцы", condition_name_id: 3},
#   {name: "стрии", condition_name_id: 3},
#   {name: "расчёсы", condition_name_id: 3},
#   {name: "ссадины", condition_name_id: 3},
#   {name: "сосудистые звездочки", condition_name_id: 3},
#   {name: "геморрагии", condition_name_id: 3},
#   {name: "отёчность", condition_name_id: 3},
#   {name: "розова", condition_name_id: 4},
#   {name: "гиперемия", condition_name_id: 4},
#   {name: "бледно-розовая", condition_name_id: 5},
#   {name: "гиперемирована", condition_name_id: 5},
#   {name: "желтушна", condition_name_id: 5},
#   {name: "бело-фарфоровая", condition_name_id: 5},
#   {name: "отёчна", condition_name_id: 5},
#   {name: "гладкая", condition_name_id: 6},
#   {name: "разрыхлена", condition_name_id: 6},
#   {name: "избыточно", condition_name_id: 7},
#   {name: "скудно", condition_name_id: 7},
#   {name: "умеренно", condition_name_id: 7},
#   {name: "не пальпируются", condition_name_id: 8},
#   {name: "не увеличены", condition_name_id: 8},
#   {name: "увеличены", condition_name_id: 8},
#   {name: "ясные", condition_name_id: 9},
#   {name: "громкие", condition_name_id: 9},
#   {name: "приглушены", condition_name_id: 9},
#   {name: "глухие", condition_name_id: 9},
#   {name: "ритмичные", condition_name_id: 9},
#   {name: "аритмичные", condition_name_id: 9},
#   {name: "экстрасистолия", condition_name_id: 9},
#   {name: "систолический", condition_name_id: 10},
#   {name: "функциональный", condition_name_id: 10},
#   {name: "органический", condition_name_id: 10},
#   {name: "на верхушке", condition_name_id: 10},
#   {name: "в т. Боткина", condition_name_id: 10},
#   {name: "над грудиной", condition_name_id: 10},
#   {name: "справа от грудины", condition_name_id: 10},
#   {name: "отсутствует", condition_name_id: 13},
#   {name: "инспираторная", condition_name_id: 13},
#   {name: "экспираторная", condition_name_id: 13},
#   {name: "возникает при", condition_name_id: 13},
#   {name: "ясный лёгочный", condition_name_id: 15},
#   {name: "притуплённый", condition_name_id: 15},
#   {name: "укороченный", condition_name_id: 15},
#   {name: "тимпанический", condition_name_id: 15},
#   {name: "коробочный", condition_name_id: 15},
#   {name: "металлический", condition_name_id: 15},
#   {name: "одностороннее", condition_name_id: 16},
#   {name: "двустороннее опущение", condition_name_id: 16},
#   {name: "смещение вверх нижних границ ", condition_name_id: 16},
#   {name: "везикулярное", condition_name_id: 17},
#   {name: "жёсткое", condition_name_id: 17},
#   {name: "ослаблено слева", condition_name_id: 17},
#   {name: "ослаблено справа", condition_name_id: 17},
#   {name: "ослаблено в верхних отделах", condition_name_id: 17},
#   {name: "ослаблено в нижних отделах", condition_name_id: 17},
#   {name: "ослаблено по передней поверхности", condition_name_id: 17},
#   {name: "ослаблено по задней поверхности", condition_name_id: 17},
#   {name: "ослаблено по боковой поверхности", condition_name_id: 17},
#   {name: "отсутствуют", condition_name_id: 18},
#   {name: "единичные", condition_name_id: 18},
#   {name: "множественные", condition_name_id: 18},
#   {name: "мелкопузырчатые", condition_name_id: 18},
#   {name: "среднепузырчатые", condition_name_id: 18},
#   {name: "крупнопузырчатые", condition_name_id: 18},
#   {name: "сухие", condition_name_id: 18},
#   {name: "влажные", condition_name_id: 18},
#   {name: "свистящие", condition_name_id: 18},
#   {name: "крепитирующие", condition_name_id: 18},
#   {name: "застойного характера", condition_name_id: 18},
#   {name: "слева", condition_name_id: 18},
#   {name: "справа", condition_name_id: 18},
#   {name: "по передней поверхности", condition_name_id: 18},
#   {name: "по задней поверхности", condition_name_id: 18},
#   {name: "по боковой поверхности", condition_name_id: 18},
#   {name: "в верхних отделах", condition_name_id: 18},
#   {name: "в средних отделах", condition_name_id: 18},
#   {name: "в нижних отделах", condition_name_id: 18},
#   {name: "влажный", condition_name_id: 21},
#   {name: "сухой", condition_name_id: 21},
#   {name: "чистый", condition_name_id: 21},
#   {name: "обложен налётом ", condition_name_id: 21},
#   {name: "увеличен за счёт п/жировой клетчатки", condition_name_id: 22},
#   {name: "увеличен за счёт отёков", condition_name_id: 22},
#   {name: "увеличен за счёт грыжевых выпячиваний", condition_name_id: 22},
#   {name: "мягкий", condition_name_id: 23},
#   {name: "безболезненный", condition_name_id: 23},
#   {name: "болезненный", condition_name_id: 23},
#   {name: "есть", condition_name_id: 24},
#   {name: "нет", condition_name_id: 24},
#   {name: "по краю рёберной дуги", condition_name_id: 25},
#   {name: "увеличена", condition_name_id: 25},
#   {name: "болезненная", condition_name_id: 25},
#   {name: "плотная", condition_name_id: 25},
#   {name: "мягкая", condition_name_id: 25},
#   {name: "поверхность гладкая", condition_name_id: 25},
#   {name: "поверхность бугристая", condition_name_id: 25},
#   {name: "увеличена", condition_name_id: 26},
#   {name: "болезненная", condition_name_id: 26},
#   {name: "нарушена", condition_name_id: 27},
#   {name: "не нарушена", condition_name_id: 27},
#   {name: "безболезненная", condition_name_id: 28},
#   {name: "болезненная", condition_name_id: 28},
#   {name: "кал оформленный", condition_name_id: 28},
#   {name: "кал жидкий", condition_name_id: 28},
#   {name: "кал коричневого цвета", condition_name_id: 28},
#   {name: "кал без примеси слизи и крови", condition_name_id: 28},
#   {name: "отрицательный", condition_name_id: 29},
#   {name: "положительный слева", condition_name_id: 29},
#   {name: "положительный справа", condition_name_id: 29},
#   {name: "положительный с обеих сторон", condition_name_id: 29},
#   {name: "4-6 раз в сутки", condition_name_id: 30},
#   {name: "безболезненное", condition_name_id: 30},
#   {name: "болезненное", condition_name_id: 30},
#   {name: "учащённое", condition_name_id: 30},
#   {name: "редкое", condition_name_id: 30},
#   {name: "никтурия", condition_name_id: 30},
#   {name: "олигурия", condition_name_id: 30},
#   {name: "анурия", condition_name_id: 30},
#   {name: "моча светло-соломенного цвета", condition_name_id: 30}
# ])
# ConditionVisit.create!([
#   {visit_id: 82, condition_value_id: 44, details: ""},
#   {visit_id: 82, condition_value_id: 45, details: ""},
#   {visit_id: 82, condition_value_id: 46, details: ""},
#   {visit_id: 82, condition_value_id: 47, details: ""},
#   {visit_id: 83, condition_value_id: 44, details: ""},
#   {visit_id: 83, condition_value_id: 45, details: ""},
#   {visit_id: 83, condition_value_id: 46, details: ""},
#   {visit_id: 83, condition_value_id: 47, details: ""},
#   {visit_id: 84, condition_value_id: 44, details: ""},
#   {visit_id: 84, condition_value_id: 45, details: ""},
#   {visit_id: 84, condition_value_id: 46, details: ""},
#   {visit_id: 84, condition_value_id: 47, details: ""},
#   {visit_id: 85, condition_value_id: 44, details: ""},
#   {visit_id: 85, condition_value_id: 45, details: ""},
#   {visit_id: 85, condition_value_id: 46, details: ""},
#   {visit_id: 85, condition_value_id: 47, details: ""},
#   {visit_id: 86, condition_value_id: 44, details: ""},
#   {visit_id: 86, condition_value_id: 45, details: ""},
#   {visit_id: 86, condition_value_id: 46, details: ""},
#   {visit_id: 86, condition_value_id: 47, details: ""},
#   {visit_id: 87, condition_value_id: 44, details: ""},
#   {visit_id: 87, condition_value_id: 45, details: ""},
#   {visit_id: 87, condition_value_id: 46, details: ""},
#   {visit_id: 87, condition_value_id: 47, details: ""},
#   {visit_id: 88, condition_value_id: 44, details: ""},
#   {visit_id: 88, condition_value_id: 45, details: ""},
#   {visit_id: 88, condition_value_id: 46, details: ""},
#   {visit_id: 88, condition_value_id: 47, details: ""}
# ])
ConstitutionOption.create!([
  {name: "Нормостеническое"},
  {name: "Астеническое"},
  {name: "Гиперстеническое"}
])
GeneralStateOption.create!([
  {name: "Удовлетворительное"},
  {name: "Средней степени тяжести"},
  {name: "Тяжелое"}
])
Examination.create!([
  {name: "ЭКГ"},
  {name: "Общий анализ крови"},
  {name: "УЗИ щитовидной железы"}
])
PosturalPoseOption.create!([
  {name: "Активное"},
  {name: "Пассивное"},
  {name: "Вынужденное"}
])
# Consultation.create!([
#   {visit_id: 81, specialist_id: 1, result: nil}
# ])
# Diagnosis.create!([
#   {name: "Диагноз0"},
#   {name: "Диагноз1"},
#   {name: "Диагноз2"},
#   {name: "Диагноз3"},
#   {name: "Диагноз4"},
#   {name: "Диагноз5"},
#   {name: "Диагноз6"},
#   {name: "Диагноз7"},
#   {name: "Диагноз8"},
#   {name: "Диагноз9"},
#   {name: "Диагноз0"},
#   {name: "Диагноз1"},
#   {name: "Диагноз2"},
#   {name: "Диагноз3"},
#   {name: "Диагноз4"},
#   {name: "Диагноз5"},
#   {name: "Диагноз6"},
#   {name: "Диагноз7"},
#   {name: "Диагноз8"},
#   {name: "Диагноз9"},
#   {name: "Диагноз0"},
#   {name: "Диагноз1"},
#   {name: "Диагноз2"},
#   {name: "Диагноз3"},
#   {name: "Диагноз4"},
#   {name: "Диагноз5"},
#   {name: "Диагноз6"},
#   {name: "Диагноз7"},
#   {name: "Диагноз8"},
#   {name: "Диагноз9"},
#   {name: "Диагноз0"},
#   {name: "Диагноз1"},
#   {name: "Диагноз2"},
#   {name: "Диагноз3"},
#   {name: "Диагноз4"},
#   {name: "Диагноз5"},
#   {name: "Диагноз6"},
#   {name: "Диагноз7"},
#   {name: "Диагноз8"},
#   {name: "Диагноз9"},
#   {name: "Диагноз0"},
#   {name: "Диагноз1"},
#   {name: "Диагноз2"},
#   {name: "Диагноз3"},
#   {name: "Диагноз4"},
#   {name: "Диагноз5"},
#   {name: "Диагноз6"},
#   {name: "Диагноз7"},
#   {name: "Диагноз8"},
#   {name: "Диагноз9"}
# ])
# EffleurageOption.create!([
#   {name: "Отрицательный"},
#   {name: "Положительный слева"},
#   {name: "Положительный справа"},
#   {name: "Положительный с обеих сторон"},
#   {name: "Отрицательный"},
#   {name: "Положительный слева"},
#   {name: "Положительный справа"},
#   {name: "Положительный с обеих сторон"}
# ])
# Examination.create!([
#   {name: "Общий анализ крови"},
#   {name: "ЭКГ"}
# ])
# GeneralStateOption.create!([
#   {name: "Удовлетворительное"},
#   {name: "Относительно удовлетворительное"},
#   {name: "Средней степени тяжести"},
#   {name: "Тяжелое"},
#   {name: "Удовлетворительное"},
#   {name: "Относительно удовлетворительное"},
#   {name: "Средней степени тяжести"},
#   {name: "Тяжелое"}
# ])
# Medicine.create!([
#   {name: "лекарство1", code: nil},
#   {name: "лекарство2", code: nil}
# ])
# Patient.create!([
#   {name: nil, age: nil, gender: "female", birthday: nil, surname: nil, second_name: nil, address: nil, registration_address: nil, phone: nil, work_phone: nil, disability: nil, work_place: nil, work_position: nil, dependant: nil, area: "urban", insurance_policy_series: nil, insurance_policy_number: nil, social_benefit_code: nil, document_series: nil, document_number: nil, martial_status: "single", education: "unknown", employment: "job", disability_time: nil, disability_date: nil, blood_type: nil, Rh_factor: "positive", insurance_company: nil, document_name: nil, insurance_certificate: nil, allergy: nil, bool_test: nil},
#   {name: "Иванова Татьяна Александровна", age: nil, gender: "female", birthday: "1984-07-04", surname: nil, second_name: nil, address: "г Астрахань, ул Кирова, д 5 ", registration_address: nil, phone: "+79343434434", work_phone: nil, disability: nil, work_place: "", work_position: "", dependant: nil, area: "urban", insurance_policy_series: "1234", insurance_policy_number: "12345678", social_benefit_code: "1", document_series: "1234", document_number: "123456", martial_status: "single", education: "unknown", employment: "job", disability_time: "primary", disability_date: nil, blood_type: "2", Rh_factor: "positive", insurance_company: "СОГАЗ", document_name: nil, insurance_certificate: "12345678900", allergy: nil, bool_test: nil},
#   {name: "Иванов Иван Иванович", age: nil, gender: "male", birthday: nil, surname: nil, second_name: nil, address: "г. Астрахань, ул. Ленина, д. 1", registration_address: nil, phone: "89875679811", work_phone: nil, disability: nil, work_place: "Завод номер 1", work_position: "Уборщик", dependant: nil, area: "urban", insurance_policy_series: "0111", insurance_policy_number: "000196411", social_benefit_code: "1", document_series: "1111", document_number: "6432511", martial_status: "married", education: "higher", employment: "job", disability_time: nil, disability_date: nil, blood_type: "1", Rh_factor: "positive", insurance_company: "СОГАЗ", document_name: nil, insurance_certificate: "4567876511", allergy: nil, bool_test: nil},
#   {name: "Петров Петр Петрович", age: nil, gender: "male", birthday: nil, surname: nil, second_name: nil, address: "г. Астрахань, ул. Зеленая, д. 1", registration_address: nil, phone: "89875679811", work_phone: nil, disability: nil, work_place: "Школа номер 1", work_position: "Учитель", dependant: nil, area: "rural", insurance_policy_series: "0211", insurance_policy_number: "000196411", social_benefit_code: "1", document_series: "1211", document_number: "6432511", martial_status: "single", education: "higher", employment: "unemployed", disability_time: nil, disability_date: nil, blood_type: "2", Rh_factor: "negative", insurance_company: "СОГАЗ", document_name: nil, insurance_certificate: "5567876511", allergy: nil, bool_test: nil},
#   {name: "Васильков Василий Васильевич", age: nil, gender: "male", birthday: "1961-02-06", surname: nil, second_name: nil, address: "г. Астрахань, ул. Теплая, д. 1", registration_address: nil, phone: "89875679811", work_phone: nil, disability: nil, work_place: "Больница номер 1", work_position: "Врач", dependant: nil, area: "urban", insurance_policy_series: "0311", insurance_policy_number: "000196411", social_benefit_code: "1", document_series: "1311", document_number: "6432511", martial_status: "married", education: "higher", employment: "job", disability_time: nil, disability_date: nil, blood_type: "3", Rh_factor: "positive", insurance_company: "СОГАЗ", document_name: nil, insurance_certificate: "6567876511", allergy: nil, bool_test: nil},
#   {name: "Дарьева Дарья Дарьевна", age: nil, gender: "female", birthday: nil, surname: nil, second_name: nil, address: "г. Астрахань, ул. Тополиная, д. 1", registration_address: nil, phone: "89875679811", work_phone: nil, disability: nil, work_place: "Фабрика номер 1", work_position: "Инженер", dependant: nil, area: "rural", insurance_policy_series: "0411", insurance_policy_number: "000196411", social_benefit_code: "1", document_series: "1411", document_number: "6432511", martial_status: "single", education: "higher", employment: "unemployed", disability_time: nil, disability_date: nil, blood_type: "4", Rh_factor: "negative", insurance_company: "СОГАЗ", document_name: nil, insurance_certificate: "7567876511", allergy: nil, bool_test: nil},
#   {name: "Васильева Василила Василисовна", age: nil, gender: "female", birthday: "1941-11-08", surname: nil, second_name: nil, address: "г. Астрахань, ул. Спортивная, д. 1", registration_address: nil, phone: "89875679811", work_phone: nil, disability: nil, work_place: "Администрация", work_position: "Инженер", dependant: nil, area: "urban", insurance_policy_series: "0511", insurance_policy_number: "000196411", social_benefit_code: "1", document_series: "1511", document_number: "6432511", martial_status: "married", education: "higher", employment: "job", disability_time: nil, disability_date: nil, blood_type: "1", Rh_factor: "positive", insurance_company: "СОГАЗ", document_name: nil, insurance_certificate: "8567876511", allergy: nil, bool_test: nil},
#   {name: "Иванов Иван Иванович", age: nil, gender: "male", birthday: nil, surname: nil, second_name: nil, address: "г. Астрахань, ул. Ленина, д. 2", registration_address: nil, phone: "89875679812", work_phone: nil, disability: nil, work_place: "Завод номер 2", work_position: "Уборщик", dependant: nil, area: "urban", insurance_policy_series: "0112", insurance_policy_number: "000196412", social_benefit_code: "2", document_series: "1112", document_number: "6432512", martial_status: "married", education: "higher", employment: "job", disability_time: nil, disability_date: nil, blood_type: "1", Rh_factor: "positive", insurance_company: "СОГАЗ", document_name: nil, insurance_certificate: "4567876512", allergy: nil, bool_test: nil},
#   {name: "Петров Петр Петрович", age: nil, gender: "male", birthday: nil, surname: nil, second_name: nil, address: "г. Астрахань, ул. Зеленая, д. 2", registration_address: nil, phone: "89875679812", work_phone: nil, disability: nil, work_place: "Школа номер 2", work_position: "Учитель", dependant: nil, area: "rural", insurance_policy_series: "0212", insurance_policy_number: "000196412", social_benefit_code: "2", document_series: "1212", document_number: "6432512", martial_status: "single", education: "higher", employment: "unemployed", disability_time: nil, disability_date: nil, blood_type: "2", Rh_factor: "negative", insurance_company: "СОГАЗ", document_name: nil, insurance_certificate: "5567876512", allergy: nil, bool_test: nil},
#   {name: "Васильков Василий Васильевич", age: nil, gender: "male", birthday: "1962-03-07", surname: nil, second_name: nil, address: "г. Астрахань, ул. Теплая, д. 2", registration_address: nil, phone: "89875679812", work_phone: nil, disability: nil, work_place: "Больница номер 2", work_position: "Врач", dependant: nil, area: "urban", insurance_policy_series: "0312", insurance_policy_number: "000196412", social_benefit_code: "2", document_series: "1312", document_number: "6432512", martial_status: "married", education: "higher", employment: "job", disability_time: nil, disability_date: nil, blood_type: "3", Rh_factor: "positive", insurance_company: "СОГАЗ", document_name: nil, insurance_certificate: "6567876512", allergy: nil, bool_test: nil},
#   {name: "Дарьева Дарья Дарьевна", age: nil, gender: "female", birthday: nil, surname: nil, second_name: nil, address: "г. Астрахань, ул. Тополиная, д. 2", registration_address: nil, phone: "89875679812", work_phone: nil, disability: nil, work_place: "Фабрика номер 2", work_position: "Инженер", dependant: nil, area: "rural", insurance_policy_series: "0412", insurance_policy_number: "000196412", social_benefit_code: "2", document_series: "1412", document_number: "6432512", martial_status: "single", education: "higher", employment: "unemployed", disability_time: nil, disability_date: nil, blood_type: "4", Rh_factor: "negative", insurance_company: "СОГАЗ", document_name: nil, insurance_certificate: "7567876512", allergy: nil, bool_test: nil},
#   {name: "Васильева Василила Василисовна", age: nil, gender: "female", birthday: "1942-12-09", surname: nil, second_name: nil, address: "г. Астрахань, ул. Спортивная, д. 2", registration_address: nil, phone: "89875679812", work_phone: nil, disability: nil, work_place: "Администрация", work_position: "Инженер", dependant: nil, area: "urban", insurance_policy_series: "0512", insurance_policy_number: "000196412", social_benefit_code: "2", document_series: "1512", document_number: "6432512", martial_status: "married", education: "higher", employment: "job", disability_time: nil, disability_date: nil, blood_type: "1", Rh_factor: "positive", insurance_company: "СОГАЗ", document_name: nil, insurance_certificate: "8567876512", allergy: nil, bool_test: nil},
#   {name: "Иванов Иван Иванович", age: nil, gender: "male", birthday: nil, surname: nil, second_name: nil, address: "г. Астрахань, ул. Ленина, д. 3", registration_address: nil, phone: "89875679813", work_phone: nil, disability: nil, work_place: "Завод номер 3", work_position: "Уборщик", dependant: nil, area: "urban", insurance_policy_series: "0113", insurance_policy_number: "000196413", social_benefit_code: "3", document_series: "1113", document_number: "6432513", martial_status: "married", education: "higher", employment: "job", disability_time: nil, disability_date: nil, blood_type: "1", Rh_factor: "positive", insurance_company: "СОГАЗ", document_name: nil, insurance_certificate: "4567876513", allergy: nil, bool_test: nil},
#   {name: "Петров Петр Петрович", age: nil, gender: "male", birthday: nil, surname: nil, second_name: nil, address: "г. Астрахань, ул. Зеленая, д. 3", registration_address: nil, phone: "89875679813", work_phone: nil, disability: nil, work_place: "Школа номер 3", work_position: "Учитель", dependant: nil, area: "rural", insurance_policy_series: "0213", insurance_policy_number: "000196413", social_benefit_code: "3", document_series: "1213", document_number: "6432513", martial_status: "single", education: "higher", employment: "unemployed", disability_time: nil, disability_date: nil, blood_type: "2", Rh_factor: "negative", insurance_company: "СОГАЗ", document_name: nil, insurance_certificate: "5567876513", allergy: nil, bool_test: nil},
#   {name: "Васильков Василий Васильевич", age: nil, gender: "male", birthday: "1963-04-08", surname: nil, second_name: nil, address: "г. Астрахань, ул. Теплая, д. 3", registration_address: nil, phone: "89875679813", work_phone: nil, disability: nil, work_place: "Больница номер 3", work_position: "Врач", dependant: nil, area: "urban", insurance_policy_series: "0313", insurance_policy_number: "000196413", social_benefit_code: "3", document_series: "1313", document_number: "6432513", martial_status: "married", education: "higher", employment: "job", disability_time: nil, disability_date: nil, blood_type: "3", Rh_factor: "positive", insurance_company: "СОГАЗ", document_name: nil, insurance_certificate: "6567876513", allergy: nil, bool_test: nil},
#   {name: "Дарьева Дарья Дарьевна", age: nil, gender: "female", birthday: nil, surname: nil, second_name: nil, address: "г. Астрахань, ул. Тополиная, д. 3", registration_address: nil, phone: "89875679813", work_phone: nil, disability: nil, work_place: "Фабрика номер 3", work_position: "Инженер", dependant: nil, area: "rural", insurance_policy_series: "0413", insurance_policy_number: "000196413", social_benefit_code: "3", document_series: "1413", document_number: "6432513", martial_status: "single", education: "higher", employment: "unemployed", disability_time: nil, disability_date: nil, blood_type: "4", Rh_factor: "negative", insurance_company: "СОГАЗ", document_name: nil, insurance_certificate: "7567876513", allergy: nil, bool_test: nil},
#   {name: "Иванов Иван Иванович", age: nil, gender: "male", birthday: nil, surname: nil, second_name: nil, address: "г. Астрахань, ул. Ленина, д. 4", registration_address: nil, phone: "89875679814", work_phone: nil, disability: nil, work_place: "Завод номер 4", work_position: "Уборщик", dependant: nil, area: "urban", insurance_policy_series: "0114", insurance_policy_number: "000196414", social_benefit_code: "4", document_series: "1114", document_number: "6432514", martial_status: "married", education: "secondary", employment: "job", disability_time: nil, disability_date: nil, blood_type: "1", Rh_factor: "positive", insurance_company: "СОГАЗ", document_name: nil, insurance_certificate: "4567876514", allergy: nil, bool_test: nil},
#   {name: "Петров Петр Петрович", age: nil, gender: "male", birthday: nil, surname: nil, second_name: nil, address: "г. Астрахань, ул. Зеленая, д. 4", registration_address: nil, phone: "89875679814", work_phone: nil, disability: nil, work_place: "Школа номер 4", work_position: "Учитель", dependant: nil, area: "rural", insurance_policy_series: "0214", insurance_policy_number: "000196414", social_benefit_code: "4", document_series: "1214", document_number: "6432514", martial_status: "single", education: "secondary", employment: "unemployed", disability_time: nil, disability_date: nil, blood_type: "2", Rh_factor: "negative", insurance_company: "СОГАЗ", document_name: nil, insurance_certificate: "5567876514", allergy: nil, bool_test: nil},
#   {name: "Васильков Василий Васильевич", age: nil, gender: "male", birthday: "1964-05-09", surname: nil, second_name: nil, address: "г. Астрахань, ул. Теплая, д. 4", registration_address: nil, phone: "89875679814", work_phone: nil, disability: nil, work_place: "Больница номер 4", work_position: "Врач", dependant: nil, area: "urban", insurance_policy_series: "0314", insurance_policy_number: "000196414", social_benefit_code: "4", document_series: "1314", document_number: "6432514", martial_status: "married", education: "secondary", employment: "job", disability_time: nil, disability_date: nil, blood_type: "3", Rh_factor: "positive", insurance_company: "СОГАЗ", document_name: nil, insurance_certificate: "6567876514", allergy: nil, bool_test: nil},
#   {name: "Дарьева Дарья Дарьевна", age: nil, gender: "female", birthday: nil, surname: nil, second_name: nil, address: "г. Астрахань, ул. Тополиная, д. 4", registration_address: nil, phone: "89875679814", work_phone: nil, disability: nil, work_place: "Фабрика номер 4", work_position: "Инженер", dependant: nil, area: "rural", insurance_policy_series: "0414", insurance_policy_number: "000196414", social_benefit_code: "4", document_series: "1414", document_number: "6432514", martial_status: "single", education: "secondary", employment: "unemployed", disability_time: nil, disability_date: nil, blood_type: "4", Rh_factor: "negative", insurance_company: "СОГАЗ", document_name: nil, insurance_certificate: "7567876514", allergy: nil, bool_test: nil},
#   {name: "Иванов Иван Иванович", age: nil, gender: "male", birthday: nil, surname: nil, second_name: nil, address: "г. Астрахань, ул. Ленина, д. 5", registration_address: nil, phone: "89875679815", work_phone: nil, disability: nil, work_place: "Завод номер 5", work_position: "Уборщик", dependant: nil, area: "urban", insurance_policy_series: "0115", insurance_policy_number: "000196415", social_benefit_code: "5", document_series: "1115", document_number: "6432515", martial_status: "married", education: "secondary", employment: "job", disability_time: nil, disability_date: nil, blood_type: "1", Rh_factor: "positive", insurance_company: "СОГАЗ", document_name: nil, insurance_certificate: "4567876515", allergy: nil, bool_test: nil},
#   {name: "Петров Петр Петрович", age: nil, gender: "male", birthday: nil, surname: nil, second_name: nil, address: "г. Астрахань, ул. Зеленая, д. 5", registration_address: nil, phone: "89875679815", work_phone: nil, disability: nil, work_place: "Школа номер 5", work_position: "Учитель", dependant: nil, area: "rural", insurance_policy_series: "0215", insurance_policy_number: "000196415", social_benefit_code: "5", document_series: "1215", document_number: "6432515", martial_status: "single", education: "secondary", employment: "unemployed", disability_time: nil, disability_date: nil, blood_type: "2", Rh_factor: "negative", insurance_company: "СОГАЗ", document_name: nil, insurance_certificate: "5567876515", allergy: nil, bool_test: nil},
#   {name: "Васильков Василий Васильевич", age: nil, gender: "male", birthday: "1965-06-10", surname: nil, second_name: nil, address: "г. Астрахань, ул. Теплая, д. 5", registration_address: nil, phone: "89875679815", work_phone: nil, disability: nil, work_place: "Больница номер 5", work_position: "Врач", dependant: nil, area: "urban", insurance_policy_series: "0315", insurance_policy_number: "000196415", social_benefit_code: "5", document_series: "1315", document_number: "6432515", martial_status: "married", education: "secondary", employment: "job", disability_time: nil, disability_date: nil, blood_type: "3", Rh_factor: "positive", insurance_company: "СОГАЗ", document_name: nil, insurance_certificate: "6567876515", allergy: nil, bool_test: nil},
#   {name: "Дарьева Дарья Дарьевна", age: nil, gender: "female", birthday: nil, surname: nil, second_name: nil, address: "г. Астрахань, ул. Тополиная, д. 5", registration_address: nil, phone: "89875679815", work_phone: nil, disability: nil, work_place: "Фабрика номер 5", work_position: "Инженер", dependant: nil, area: "rural", insurance_policy_series: "0415", insurance_policy_number: "000196415", social_benefit_code: "5", document_series: "1415", document_number: "6432515", martial_status: "single", education: "secondary", employment: "unemployed", disability_time: nil, disability_date: nil, blood_type: "4", Rh_factor: "negative", insurance_company: "СОГАЗ", document_name: nil, insurance_certificate: "7567876515", allergy: nil, bool_test: nil},
#   {name: "Васильева Василила Василисовна", age: nil, gender: "female", birthday: nil, surname: nil, second_name: nil, address: "г. Астрахань, ул. Спортивная, д. 5", registration_address: nil, phone: "89875679815", work_phone: nil, disability: nil, work_place: "Администрация", work_position: "Инженер", dependant: nil, area: "urban", insurance_policy_series: "0515", insurance_policy_number: "000196415", social_benefit_code: "5", document_series: "1515", document_number: "6432515", martial_status: "married", education: "secondary", employment: "job", disability_time: nil, disability_date: nil, blood_type: "1", Rh_factor: "positive", insurance_company: "СОГАЗ", document_name: nil, insurance_certificate: "8567876515", allergy: nil, bool_test: nil},
#   {name: "Васильева Василила Василисовна", age: nil, gender: "female", birthday: nil, surname: nil, second_name: nil, address: "г. Астрахань, ул. Спортивная, д. 3", registration_address: nil, phone: "89875679813", work_phone: nil, disability: nil, work_place: "Администрация", work_position: "Инженер", dependant: nil, area: "urban", insurance_policy_series: "0513", insurance_policy_number: "000196413", social_benefit_code: "3", document_series: "1513", document_number: "6432513", martial_status: "married", education: "secondary", employment: "job", disability_time: nil, disability_date: nil, blood_type: "1", Rh_factor: "positive", insurance_company: "СОГАЗ", document_name: nil, insurance_certificate: "8567876513", allergy: nil, bool_test: nil},
#   {name: "Васильева Василила Василисовна", age: nil, gender: "female", birthday: nil, surname: nil, second_name: nil, address: "г. Астрахань, ул. Спортивная, д. 4", registration_address: nil, phone: "89875679814", work_phone: nil, disability: nil, work_place: "Администрация", work_position: "Инженер", dependant: nil, area: "urban", insurance_policy_series: "0514", insurance_policy_number: "000196414", social_benefit_code: "4", document_series: "1514", document_number: "6432514", martial_status: "married", education: "secondary", employment: "job", disability_time: nil, disability_date: nil, blood_type: "1", Rh_factor: "positive", insurance_company: "СОГАЗ", document_name: nil, insurance_certificate: "8567876514", allergy: nil, bool_test: nil}
# ])
# PosturalPoseOption.create!([
#   {name: "Активное"},
#   {name: "Пассивное"},
#   {name: "Вынужденное"}
# ])
# PrimaryDiagnosis.create!([
#   {name: "Диагноз0"},
#   {name: "Диагноз1"},
#   {name: "Диагноз2"},
#   {name: "Диагноз3"},
#   {name: "Диагноз4"},
#   {name: "Диагноз5"},
#   {name: "Диагноз6"},
#   {name: "Диагноз7"},
#   {name: "Диагноз8"},
#   {name: "Диагноз9"},
#   {name: "Диагноз0"},
#   {name: "Диагноз1"},
#   {name: "Диагноз2"},
#   {name: "Диагноз3"},
#   {name: "Диагноз4"},
#   {name: "Диагноз5"},
#   {name: "Диагноз6"},
#   {name: "Диагноз7"},
#   {name: "Диагноз8"},
#   {name: "Диагноз9"},
#   {name: "Диагноз0"},
#   {name: "Диагноз1"},
#   {name: "Диагноз2"},
#   {name: "Диагноз3"},
#   {name: "Диагноз4"},
#   {name: "Диагноз5"},
#   {name: "Диагноз6"},
#   {name: "Диагноз7"},
#   {name: "Диагноз8"},
#   {name: "Диагноз9"},
#   {name: "Диагноз0"},
#   {name: "Диагноз1"},
#   {name: "Диагноз2"},
#   {name: "Диагноз3"},
#   {name: "Диагноз4"},
#   {name: "Диагноз5"},
#   {name: "Диагноз6"},
#   {name: "Диагноз7"},
#   {name: "Диагноз8"},
#   {name: "Диагноз9"},
#   {name: "Диагноз0"},
#   {name: "Диагноз1"},
#   {name: "Диагноз2"},
#   {name: "Диагноз3"},
#   {name: "Диагноз4"},
#   {name: "Диагноз5"},
#   {name: "Диагноз6"},
#   {name: "Диагноз7"},
#   {name: "Диагноз8"},
#   {name: "Диагноз9"}
# ])
# PrimaryDiagnosisVisit.create!([
#   {visit_id: 29, primary_diagnosis_id: 1, details: "1"},
#   {visit_id: 29, primary_diagnosis_id: 2, details: "2"},
#   {visit_id: 30, primary_diagnosis_id: 1, details: "3"},
#   {visit_id: 30, primary_diagnosis_id: 2, details: "4"},
#   {visit_id: 30, primary_diagnosis_id: 3, details: "5"},
#   {visit_id: 31, primary_diagnosis_id: 1, details: "6"},
#   {visit_id: 29, primary_diagnosis_id: 1, details: "1"},
#   {visit_id: 29, primary_diagnosis_id: 2, details: "2"},
#   {visit_id: 30, primary_diagnosis_id: 1, details: "3"},
#   {visit_id: 30, primary_diagnosis_id: 2, details: "4"},
#   {visit_id: 30, primary_diagnosis_id: 3, details: "5"},
#   {visit_id: 31, primary_diagnosis_id: 1, details: "6"}
# ])
# Specialist.create!([
#   {name: "Терапевт"},
#   {name: "Физиотерапевт"}
# ])

# (1..5).each do |i|
# 	Patient.create!([
# 		{name: "Иванов Иван Иванович", :gender => :male, birthday: "#{1980+i}-#{14+i}-#{1+i}", address: "г. Астрахань, ул. Ленина, д. #{i}", phone: "898756798#{i+10}", work_place: "Завод номер #{i}", work_position: "Уборщик", area: "urban", insurance_policy_series: "01#{10+i}", insurance_policy_number: "0001964#{10+i}", social_benefit_code: "#{i}", document_series: "11#{10+i}", document_number: "64325#{10+i}", martial_status: "married", education: "higher", employment: "job", blood_type: "1", :Rh_factor => "positive", insurance_company: "СОГАЗ", insurance_certificate: "45678765#{i+10}"},
# 		{name: "Петров Петр Петрович", :gender => :male, birthday: "#{1970+i}-#{20+i}-#{2+i}", address: "г. Астрахань, ул. Зеленая, д. #{i}", phone: "898756798#{i+10}", work_place: "Школа номер #{i}", work_position: "Учитель", area: "rural", insurance_policy_series: "02#{10+i}", insurance_policy_number: "0001964#{10+i}", social_benefit_code: "#{i}", document_series: "12#{10+i}", document_number: "64325#{10+i}", martial_status: "single", education: "higher", employment: "unemployed", blood_type: "2", :Rh_factor => "negative", insurance_company: "СОГАЗ", insurance_certificate: "55678765#{i+10}"},
# 		{name: "Васильков Василий Васильевич", :gender => :male, birthday: "#{1960+i}-#{1+i}-#{5+i}", address: "г. Астрахань, ул. Теплая, д. #{i}", phone: "898756798#{i+10}", work_place: "Больница номер #{i}", work_position: "Врач", area: "urban", insurance_policy_series: "03#{10+i}", insurance_policy_number: "0001964#{10+i}", social_benefit_code: "#{i}", document_series: "13#{10+i}", document_number: "64325#{10+i}", martial_status: "married", education: "higher", employment: "job", blood_type: "3", :Rh_factor => "positive", insurance_company: "СОГАЗ", insurance_certificate: "65678765#{i+10}"},
# 		{name: "Дарьева Дарья Дарьевна", :gender => :female, birthday: "#{1950+i}-#{14+i}-#{6+i}", address: "г. Астрахань, ул. Тополиная, д. #{i}", phone: "898756798#{i+10}", work_place: "Фабрика номер #{i}", work_position: "Инженер", area: "rural", insurance_policy_series: "04#{10+i}", insurance_policy_number: "0001964#{10+i}", social_benefit_code: "#{i}", document_series: "14#{10+i}", document_number: "64325#{10+i}", martial_status: "single", education: "higher", employment: "unemployed", blood_type: "4", :Rh_factor => "negative", insurance_company: "СОГАЗ", insurance_certificate: "75678765#{i+10}"},
# 		{name: "Васильева Василила Василисовна", :gender => :female, birthday: "#{1940+i}-#{10+i}-#{7+i}", address: "г. Астрахань, ул. Спортивная, д. #{i}", phone: "898756798#{i+10}", work_place: "Администрация", work_position: "Инженер", area: "urban", insurance_policy_series: "05#{10+i}", insurance_policy_number: "0001964#{10+i}", social_benefit_code: "#{i}", document_series: "15#{10+i}", document_number: "64325#{10+i}", martial_status: "married", education: "higher", employment: "job", blood_type: "1", :Rh_factor => "positive", insurance_company: "СОГАЗ", insurance_certificate: "85678765#{i+10}"}
# 	])
# end

# Treatment.create!([
#   {treatment_factor_id: 2, amount: 2, details: "1", visit_id: 29},
#   {treatment_factor_id: 1, amount: 2, details: "1", visit_id: 29},
#   {treatment_factor_id: 2, amount: 2, details: "1", visit_id: 30},
#   {treatment_factor_id: 1, amount: 2, details: "1", visit_id: 30},
#   {treatment_factor_id: 2, amount: 2, details: "1", visit_id: 31},
#   {treatment_factor_id: 1, amount: 2, details: "1", visit_id: 31},
#   {treatment_factor_id: 2, amount: 2, details: "1", visit_id: 32}
# ])
TreatmentFactor.create!([
  {name: "Массаж"},
  {name: "Электрофорез"}
])
Specialist.create!([
  {name: "Терапевт"},
  {name: "Физиотерапевт"},
  {name: "Эндокринолог"}
])



# Visit.create!([
#   {complaints: nil, anamnesis: nil, allerg: "", general_state: nil, diagnosis: nil, doctor_id: 1, patient_id: 1, constitution_option_id: 1, general_state_option_id: 2, postural_pose_option_id: 1, subcutanious_fat_option_id: 2, effleurage_option_id: nil, from_id: 1, an_morbi: "", height: "179", weight: "79", temp: "36.6", next: nil, secondary: false, bool_test: nil},
#   {complaints: nil, anamnesis: nil, allerg: "", general_state: nil, diagnosis: nil, doctor_id: 1, patient_id: 1, constitution_option_id: 2, general_state_option_id: 1, postural_pose_option_id: 2, subcutanious_fat_option_id: 1, effleurage_option_id: nil, from_id: 2, an_morbi: "анамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнез", height: "151", weight: "61", temp: "36.6", next: nil, secondary: false, bool_test: nil},
#   {complaints: nil, anamnesis: nil, allerg: "", general_state: nil, diagnosis: nil, doctor_id: 1, patient_id: 2, constitution_option_id: 1, general_state_option_id: 2, postural_pose_option_id: 1, subcutanious_fat_option_id: 2, effleurage_option_id: nil, from_id: 1, an_morbi: "анамнез", height: "178", weight: "78", temp: "36.6", next: nil, secondary: false, bool_test: nil},
#   {complaints: nil, anamnesis: nil, allerg: "", general_state: nil, diagnosis: nil, doctor_id: 1, patient_id: 2, constitution_option_id: 2, general_state_option_id: 1, postural_pose_option_id: 2, subcutanious_fat_option_id: 1, effleurage_option_id: nil, from_id: 2, an_morbi: "анамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнез", height: "152", weight: "62", temp: "36.6", next: nil, secondary: false, bool_test: nil},
#   {complaints: nil, anamnesis: nil, allerg: "", general_state: nil, diagnosis: nil, doctor_id: 1, patient_id: 3, constitution_option_id: 1, general_state_option_id: 2, postural_pose_option_id: 1, subcutanious_fat_option_id: 2, effleurage_option_id: nil, from_id: 1, an_morbi: "анамнезанамнез", height: "177", weight: "77", temp: "36.6", next: nil, secondary: false, bool_test: nil},
#   {complaints: nil, anamnesis: nil, allerg: "", general_state: nil, diagnosis: nil, doctor_id: 1, patient_id: 3, constitution_option_id: 2, general_state_option_id: 1, postural_pose_option_id: 2, subcutanious_fat_option_id: 1, effleurage_option_id: nil, from_id: 2, an_morbi: "анамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнез", height: "153", weight: "63", temp: "36.6", next: nil, secondary: false, bool_test: nil},
#   {complaints: nil, anamnesis: nil, allerg: "", general_state: nil, diagnosis: nil, doctor_id: 1, patient_id: 4, constitution_option_id: 1, general_state_option_id: 2, postural_pose_option_id: 1, subcutanious_fat_option_id: 2, effleurage_option_id: nil, from_id: 1, an_morbi: "анамнезанамнезанамнез", height: "176", weight: "76", temp: "36.6", next: nil, secondary: false, bool_test: nil},
#   {complaints: nil, anamnesis: nil, allerg: "", general_state: nil, diagnosis: nil, doctor_id: 1, patient_id: 4, constitution_option_id: 2, general_state_option_id: 1, postural_pose_option_id: 2, subcutanious_fat_option_id: 1, effleurage_option_id: nil, from_id: 2, an_morbi: "анамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнез", height: "154", weight: "64", temp: "36.6", next: nil, secondary: false, bool_test: nil},
#   {complaints: nil, anamnesis: nil, allerg: "", general_state: nil, diagnosis: nil, doctor_id: 1, patient_id: 5, constitution_option_id: 1, general_state_option_id: 2, postural_pose_option_id: 1, subcutanious_fat_option_id: 2, effleurage_option_id: nil, from_id: 1, an_morbi: "анамнезанамнезанамнезанамнез", height: "175", weight: "75", temp: "36.6", next: nil, secondary: false, bool_test: nil},
#   {complaints: nil, anamnesis: nil, allerg: "", general_state: nil, diagnosis: nil, doctor_id: 1, patient_id: 5, constitution_option_id: 2, general_state_option_id: 1, postural_pose_option_id: 2, subcutanious_fat_option_id: 1, effleurage_option_id: nil, from_id: 2, an_morbi: "анамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнез", height: "155", weight: "65", temp: "36.6", next: nil, secondary: false, bool_test: nil},
#   {complaints: nil, anamnesis: nil, allerg: "", general_state: nil, diagnosis: nil, doctor_id: 1, patient_id: 6, constitution_option_id: 1, general_state_option_id: 2, postural_pose_option_id: 1, subcutanious_fat_option_id: 2, effleurage_option_id: nil, from_id: 1, an_morbi: "анамнезанамнезанамнезанамнезанамнез", height: "174", weight: "74", temp: "36.6", next: nil, secondary: false, bool_test: nil},
#   {complaints: nil, anamnesis: nil, allerg: "", general_state: nil, diagnosis: nil, doctor_id: 1, patient_id: 6, constitution_option_id: 2, general_state_option_id: 1, postural_pose_option_id: 2, subcutanious_fat_option_id: 1, effleurage_option_id: nil, from_id: 2, an_morbi: "анамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнез", height: "156", weight: "66", temp: "36.6", next: nil, secondary: false, bool_test: nil},
#   {complaints: nil, anamnesis: nil, allerg: "", general_state: nil, diagnosis: nil, doctor_id: 1, patient_id: 7, constitution_option_id: 1, general_state_option_id: 2, postural_pose_option_id: 1, subcutanious_fat_option_id: 2, effleurage_option_id: nil, from_id: 1, an_morbi: "анамнезанамнезанамнезанамнезанамнезанамнез", height: "173", weight: "73", temp: "36.6", next: nil, secondary: false, bool_test: nil},
#   {complaints: nil, anamnesis: nil, allerg: "", general_state: nil, diagnosis: nil, doctor_id: 1, patient_id: 7, constitution_option_id: 2, general_state_option_id: 1, postural_pose_option_id: 2, subcutanious_fat_option_id: 1, effleurage_option_id: nil, from_id: 2, an_morbi: "анамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнез", height: "157", weight: "67", temp: "36.6", next: nil, secondary: false, bool_test: nil},
#   {complaints: nil, anamnesis: nil, allerg: "", general_state: nil, diagnosis: nil, doctor_id: 1, patient_id: 8, constitution_option_id: 1, general_state_option_id: 2, postural_pose_option_id: 1, subcutanious_fat_option_id: 2, effleurage_option_id: nil, from_id: 1, an_morbi: "анамнезанамнезанамнезанамнезанамнезанамнезанамнез", height: "172", weight: "72", temp: "36.6", next: nil, secondary: false, bool_test: nil},
#   {complaints: nil, anamnesis: nil, allerg: "", general_state: nil, diagnosis: nil, doctor_id: 1, patient_id: 8, constitution_option_id: 2, general_state_option_id: 1, postural_pose_option_id: 2, subcutanious_fat_option_id: 1, effleurage_option_id: nil, from_id: 2, an_morbi: "анамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнез", height: "158", weight: "68", temp: "36.6", next: nil, secondary: false, bool_test: nil},
#   {complaints: nil, anamnesis: nil, allerg: "", general_state: nil, diagnosis: nil, doctor_id: 1, patient_id: 9, constitution_option_id: 1, general_state_option_id: 2, postural_pose_option_id: 1, subcutanious_fat_option_id: 2, effleurage_option_id: nil, from_id: 1, an_morbi: "анамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнез", height: "171", weight: "71", temp: "36.6", next: nil, secondary: false, bool_test: nil},
#   {complaints: nil, anamnesis: nil, allerg: "", general_state: nil, diagnosis: nil, doctor_id: 1, patient_id: 9, constitution_option_id: 2, general_state_option_id: 1, postural_pose_option_id: 2, subcutanious_fat_option_id: 1, effleurage_option_id: nil, from_id: 2, an_morbi: "анамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнез", height: "159", weight: "69", temp: "36.6", next: nil, secondary: false, bool_test: nil},
#   {complaints: nil, anamnesis: nil, allerg: "", general_state: nil, diagnosis: nil, doctor_id: 1, patient_id: 10, constitution_option_id: 1, general_state_option_id: 2, postural_pose_option_id: 1, subcutanious_fat_option_id: 2, effleurage_option_id: nil, from_id: 1, an_morbi: "анамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнез", height: "170", weight: "70", temp: "36.6", next: nil, secondary: false, bool_test: nil},
#   {complaints: nil, anamnesis: nil, allerg: "", general_state: nil, diagnosis: nil, doctor_id: 1, patient_id: 10, constitution_option_id: 2, general_state_option_id: 1, postural_pose_option_id: 2, subcutanious_fat_option_id: 1, effleurage_option_id: nil, from_id: 2, an_morbi: "анамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнез", height: "160", weight: "70", temp: "36.6", next: nil, secondary: false, bool_test: nil},
#   {complaints: nil, anamnesis: nil, allerg: "", general_state: nil, diagnosis: nil, doctor_id: 1, patient_id: 11, constitution_option_id: 1, general_state_option_id: 2, postural_pose_option_id: 1, subcutanious_fat_option_id: 2, effleurage_option_id: nil, from_id: 1, an_morbi: "анамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнез", height: "169", weight: "69", temp: "36.6", next: nil, secondary: false, bool_test: nil},
#   {complaints: nil, anamnesis: nil, allerg: "", general_state: nil, diagnosis: nil, doctor_id: 1, patient_id: 11, constitution_option_id: 2, general_state_option_id: 1, postural_pose_option_id: 2, subcutanious_fat_option_id: 1, effleurage_option_id: nil, from_id: 2, an_morbi: "анамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнез", height: "161", weight: "71", temp: "36.6", next: nil, secondary: false, bool_test: nil},
#   {complaints: nil, anamnesis: nil, allerg: "", general_state: nil, diagnosis: nil, doctor_id: 1, patient_id: 12, constitution_option_id: 1, general_state_option_id: 2, postural_pose_option_id: 1, subcutanious_fat_option_id: 2, effleurage_option_id: nil, from_id: 1, an_morbi: "анамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнез", height: "168", weight: "68", temp: "36.6", next: nil, secondary: false, bool_test: nil},
#   {complaints: nil, anamnesis: nil, allerg: "", general_state: nil, diagnosis: nil, doctor_id: 1, patient_id: 12, constitution_option_id: 2, general_state_option_id: 1, postural_pose_option_id: 2, subcutanious_fat_option_id: 1, effleurage_option_id: nil, from_id: 2, an_morbi: "анамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнез", height: "162", weight: "72", temp: "36.6", next: nil, secondary: false, bool_test: nil},
#   {complaints: nil, anamnesis: nil, allerg: "", general_state: nil, diagnosis: nil, doctor_id: 1, patient_id: 13, constitution_option_id: 1, general_state_option_id: 2, postural_pose_option_id: 1, subcutanious_fat_option_id: 2, effleurage_option_id: nil, from_id: 1, an_morbi: "анамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнез", height: "167", weight: "67", temp: "36.6", next: nil, secondary: false, bool_test: nil},
#   {complaints: nil, anamnesis: nil, allerg: "", general_state: nil, diagnosis: nil, doctor_id: 1, patient_id: 13, constitution_option_id: 2, general_state_option_id: 1, postural_pose_option_id: 2, subcutanious_fat_option_id: 1, effleurage_option_id: nil, from_id: 2, an_morbi: "анамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнез", height: "163", weight: "73", temp: "36.6", next: nil, secondary: false, bool_test: nil},
#   {complaints: nil, anamnesis: nil, allerg: "", general_state: nil, diagnosis: nil, doctor_id: 1, patient_id: 14, constitution_option_id: 1, general_state_option_id: 2, postural_pose_option_id: 1, subcutanious_fat_option_id: 2, effleurage_option_id: nil, from_id: 1, an_morbi: "анамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнез", height: "166", weight: "66", temp: "36.6", next: nil, secondary: false, bool_test: nil},
#   {complaints: nil, anamnesis: nil, allerg: "", general_state: nil, diagnosis: nil, doctor_id: 1, patient_id: 14, constitution_option_id: 2, general_state_option_id: 1, postural_pose_option_id: 2, subcutanious_fat_option_id: 1, effleurage_option_id: nil, from_id: 2, an_morbi: "анамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнез", height: "164", weight: "74", temp: "36.6", next: nil, secondary: false, bool_test: nil},
#   {complaints: nil, anamnesis: nil, allerg: "", general_state: nil, diagnosis: nil, doctor_id: 1, patient_id: 15, constitution_option_id: 1, general_state_option_id: 2, postural_pose_option_id: 1, subcutanious_fat_option_id: 2, effleurage_option_id: nil, from_id: 1, an_morbi: "анамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнез", height: "165", weight: "65", temp: "36.6", next: nil, secondary: false, bool_test: nil},
#   {complaints: nil, anamnesis: nil, allerg: "", general_state: nil, diagnosis: nil, doctor_id: 1, patient_id: 15, constitution_option_id: 2, general_state_option_id: 1, postural_pose_option_id: 2, subcutanious_fat_option_id: 1, effleurage_option_id: nil, from_id: 2, an_morbi: "анамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнез", height: "165", weight: "75", temp: "36.6", next: nil, secondary: false, bool_test: nil},
#   {complaints: nil, anamnesis: nil, allerg: "", general_state: nil, diagnosis: nil, doctor_id: 1, patient_id: 16, constitution_option_id: 1, general_state_option_id: 2, postural_pose_option_id: 1, subcutanious_fat_option_id: 2, effleurage_option_id: nil, from_id: 1, an_morbi: "анамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнез", height: "164", weight: "64", temp: "36.6", next: nil, secondary: false, bool_test: nil},
#   {complaints: nil, anamnesis: nil, allerg: "", general_state: nil, diagnosis: nil, doctor_id: 1, patient_id: 16, constitution_option_id: 2, general_state_option_id: 1, postural_pose_option_id: 2, subcutanious_fat_option_id: 1, effleurage_option_id: nil, from_id: 2, an_morbi: "анамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнез", height: "166", weight: "76", temp: "36.6", next: nil, secondary: false, bool_test: nil},
#   {complaints: nil, anamnesis: nil, allerg: "", general_state: nil, diagnosis: nil, doctor_id: 1, patient_id: 17, constitution_option_id: 1, general_state_option_id: 2, postural_pose_option_id: 1, subcutanious_fat_option_id: 2, effleurage_option_id: nil, from_id: 1, an_morbi: "анамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнез", height: "163", weight: "63", temp: "36.6", next: nil, secondary: false, bool_test: nil},
#   {complaints: nil, anamnesis: nil, allerg: "", general_state: nil, diagnosis: nil, doctor_id: 1, patient_id: 17, constitution_option_id: 2, general_state_option_id: 1, postural_pose_option_id: 2, subcutanious_fat_option_id: 1, effleurage_option_id: nil, from_id: 2, an_morbi: "анамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнез", height: "167", weight: "77", temp: "36.6", next: nil, secondary: false, bool_test: nil},
#   {complaints: nil, anamnesis: nil, allerg: "", general_state: nil, diagnosis: nil, doctor_id: 1, patient_id: 18, constitution_option_id: 1, general_state_option_id: 2, postural_pose_option_id: 1, subcutanious_fat_option_id: 2, effleurage_option_id: nil, from_id: 1, an_morbi: "анамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнез", height: "162", weight: "62", temp: "36.6", next: nil, secondary: false, bool_test: nil},
#   {complaints: nil, anamnesis: nil, allerg: "", general_state: nil, diagnosis: nil, doctor_id: 1, patient_id: 18, constitution_option_id: 2, general_state_option_id: 1, postural_pose_option_id: 2, subcutanious_fat_option_id: 1, effleurage_option_id: nil, from_id: 2, an_morbi: "анамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнез", height: "168", weight: "78", temp: "36.6", next: nil, secondary: false, bool_test: nil},
#   {complaints: nil, anamnesis: nil, allerg: "", general_state: nil, diagnosis: nil, doctor_id: 1, patient_id: 19, constitution_option_id: 1, general_state_option_id: 2, postural_pose_option_id: 1, subcutanious_fat_option_id: 2, effleurage_option_id: nil, from_id: 1, an_morbi: "анамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнез", height: "161", weight: "61", temp: "36.6", next: nil, secondary: false, bool_test: nil},
#   {complaints: nil, anamnesis: nil, allerg: "", general_state: nil, diagnosis: nil, doctor_id: 1, patient_id: 19, constitution_option_id: 2, general_state_option_id: 1, postural_pose_option_id: 2, subcutanious_fat_option_id: 1, effleurage_option_id: nil, from_id: 2, an_morbi: "анамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнез", height: "169", weight: "79", temp: "36.6", next: nil, secondary: false, bool_test: nil},
#   {complaints: nil, anamnesis: nil, allerg: "", general_state: nil, diagnosis: nil, doctor_id: 1, patient_id: 20, constitution_option_id: 1, general_state_option_id: 2, postural_pose_option_id: 1, subcutanious_fat_option_id: 2, effleurage_option_id: nil, from_id: 1, an_morbi: "анамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнез", height: "160", weight: "60", temp: "36.6", next: nil, secondary: false, bool_test: nil},
#   {complaints: nil, anamnesis: nil, allerg: "", general_state: nil, diagnosis: nil, doctor_id: 1, patient_id: 20, constitution_option_id: 2, general_state_option_id: 1, postural_pose_option_id: 2, subcutanious_fat_option_id: 1, effleurage_option_id: nil, from_id: 2, an_morbi: "анамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнез", height: "170", weight: "80", temp: "36.6", next: nil, secondary: false, bool_test: nil},
#   {complaints: nil, anamnesis: nil, allerg: "", general_state: nil, diagnosis: nil, doctor_id: 1, patient_id: 21, constitution_option_id: 1, general_state_option_id: 2, postural_pose_option_id: 1, subcutanious_fat_option_id: 2, effleurage_option_id: nil, from_id: 1, an_morbi: "анамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнез", height: "159", weight: "59", temp: "36.6", next: nil, secondary: false, bool_test: nil},
#   {complaints: nil, anamnesis: nil, allerg: "", general_state: nil, diagnosis: nil, doctor_id: 1, patient_id: 21, constitution_option_id: 2, general_state_option_id: 1, postural_pose_option_id: 2, subcutanious_fat_option_id: 1, effleurage_option_id: nil, from_id: 2, an_morbi: "анамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнез", height: "171", weight: "81", temp: "36.6", next: nil, secondary: false, bool_test: nil},
#   {complaints: nil, anamnesis: nil, allerg: "", general_state: nil, diagnosis: nil, doctor_id: 1, patient_id: 22, constitution_option_id: 1, general_state_option_id: 2, postural_pose_option_id: 1, subcutanious_fat_option_id: 2, effleurage_option_id: nil, from_id: 1, an_morbi: "анамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнез", height: "158", weight: "58", temp: "36.6", next: nil, secondary: false, bool_test: nil},
#   {complaints: nil, anamnesis: nil, allerg: "", general_state: nil, diagnosis: nil, doctor_id: 1, patient_id: 22, constitution_option_id: 2, general_state_option_id: 1, postural_pose_option_id: 2, subcutanious_fat_option_id: 1, effleurage_option_id: nil, from_id: 2, an_morbi: "анамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнез", height: "172", weight: "82", temp: "36.6", next: nil, secondary: false, bool_test: nil},
#   {complaints: nil, anamnesis: nil, allerg: "", general_state: nil, diagnosis: nil, doctor_id: 1, patient_id: 23, constitution_option_id: 1, general_state_option_id: 2, postural_pose_option_id: 1, subcutanious_fat_option_id: 2, effleurage_option_id: nil, from_id: 1, an_morbi: "анамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнез", height: "157", weight: "57", temp: "36.6", next: nil, secondary: false, bool_test: nil},
#   {complaints: nil, anamnesis: nil, allerg: "", general_state: nil, diagnosis: nil, doctor_id: 1, patient_id: 23, constitution_option_id: 2, general_state_option_id: 1, postural_pose_option_id: 2, subcutanious_fat_option_id: 1, effleurage_option_id: nil, from_id: 2, an_morbi: "анамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнез", height: "173", weight: "83", temp: "36.6", next: nil, secondary: false, bool_test: nil},
#   {complaints: nil, anamnesis: nil, allerg: "", general_state: nil, diagnosis: nil, doctor_id: 1, patient_id: 24, constitution_option_id: 1, general_state_option_id: 2, postural_pose_option_id: 1, subcutanious_fat_option_id: 2, effleurage_option_id: nil, from_id: 1, an_morbi: "анамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнез", height: "156", weight: "56", temp: "36.6", next: nil, secondary: false, bool_test: nil},
#   {complaints: nil, anamnesis: nil, allerg: "", general_state: nil, diagnosis: nil, doctor_id: 1, patient_id: 24, constitution_option_id: 2, general_state_option_id: 1, postural_pose_option_id: 2, subcutanious_fat_option_id: 1, effleurage_option_id: nil, from_id: 2, an_morbi: "анамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнез", height: "174", weight: "84", temp: "36.6", next: nil, secondary: false, bool_test: nil},
#   {complaints: nil, anamnesis: nil, allerg: "", general_state: nil, diagnosis: nil, doctor_id: 1, patient_id: 25, constitution_option_id: 1, general_state_option_id: 2, postural_pose_option_id: 1, subcutanious_fat_option_id: 2, effleurage_option_id: nil, from_id: 1, an_morbi: "анамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнез", height: "155", weight: "55", temp: "36.6", next: nil, secondary: false, bool_test: nil},
#   {complaints: nil, anamnesis: nil, allerg: "", general_state: nil, diagnosis: nil, doctor_id: 1, patient_id: 25, constitution_option_id: 2, general_state_option_id: 1, postural_pose_option_id: 2, subcutanious_fat_option_id: 1, effleurage_option_id: nil, from_id: 2, an_morbi: "анамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнез", height: "175", weight: "85", temp: "36.6", next: nil, secondary: false, bool_test: nil},
#   {complaints: nil, anamnesis: nil, allerg: "", general_state: nil, diagnosis: nil, doctor_id: 1, patient_id: 26, constitution_option_id: 1, general_state_option_id: 2, postural_pose_option_id: 1, subcutanious_fat_option_id: 2, effleurage_option_id: nil, from_id: 1, an_morbi: "анамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнез", height: "154", weight: "54", temp: "36.6", next: nil, secondary: false, bool_test: nil},
#   {complaints: nil, anamnesis: nil, allerg: "", general_state: nil, diagnosis: nil, doctor_id: 1, patient_id: 26, constitution_option_id: 2, general_state_option_id: 1, postural_pose_option_id: 2, subcutanious_fat_option_id: 1, effleurage_option_id: nil, from_id: 2, an_morbi: "анамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнез", height: "176", weight: "86", temp: "36.6", next: nil, secondary: false, bool_test: nil},
#   {complaints: nil, anamnesis: nil, allerg: "", general_state: nil, diagnosis: nil, doctor_id: 1, patient_id: 27, constitution_option_id: 1, general_state_option_id: 2, postural_pose_option_id: 1, subcutanious_fat_option_id: 2, effleurage_option_id: nil, from_id: 1, an_morbi: "анамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнез", height: "153", weight: "53", temp: "36.6", next: nil, secondary: false, bool_test: nil},
#   {complaints: nil, anamnesis: nil, allerg: "", general_state: nil, diagnosis: nil, doctor_id: 1, patient_id: 27, constitution_option_id: 2, general_state_option_id: 1, postural_pose_option_id: 2, subcutanious_fat_option_id: 1, effleurage_option_id: nil, from_id: 2, an_morbi: "анамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнезанамнез", height: "177", weight: "87", temp: "36.6", next: nil, secondary: false, bool_test: nil}
# ])

# (1..27).each do |i|
# Visit.create!([
	
#   {an_morbi: "#{'анамнез'*(i-1)}", allerg: "", doctor_id: 1, patient_id: i, constitution_option_id: 1, general_state_option_id: 2, postural_pose_option_id: 1, subcutanious_fat_option_id: 2, from_id: 1, height: 180-i, weight: 80-i, temp: 36.6},
#   {an_morbi: "#{'анамнез'*(i+10)}", allerg: "", doctor_id: 1, patient_id: i, constitution_option_id: 2, general_state_option_id: 1, postural_pose_option_id: 2, subcutanious_fat_option_id: 1, from_id: 2, height: 150+i, weight: 60+i, temp: 36.6},
#  ])
# end



# (17..27).each do |i|
#  	p = Patient.find(i)
#  	p.education = :secondary
#  	p.save
#  end

