require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe EffleurageOptionsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # EffleurageOption. As you add validations to EffleurageOption, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EffleurageOptionsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all effleurage_options as @effleurage_options" do
      effleurage_option = EffleurageOption.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:effleurage_options)).to eq([effleurage_option])
    end
  end

  describe "GET #show" do
    it "assigns the requested effleurage_option as @effleurage_option" do
      effleurage_option = EffleurageOption.create! valid_attributes
      get :show, {:id => effleurage_option.to_param}, valid_session
      expect(assigns(:effleurage_option)).to eq(effleurage_option)
    end
  end

  describe "GET #new" do
    it "assigns a new effleurage_option as @effleurage_option" do
      get :new, {}, valid_session
      expect(assigns(:effleurage_option)).to be_a_new(EffleurageOption)
    end
  end

  describe "GET #edit" do
    it "assigns the requested effleurage_option as @effleurage_option" do
      effleurage_option = EffleurageOption.create! valid_attributes
      get :edit, {:id => effleurage_option.to_param}, valid_session
      expect(assigns(:effleurage_option)).to eq(effleurage_option)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new EffleurageOption" do
        expect {
          post :create, {:effleurage_option => valid_attributes}, valid_session
        }.to change(EffleurageOption, :count).by(1)
      end

      it "assigns a newly created effleurage_option as @effleurage_option" do
        post :create, {:effleurage_option => valid_attributes}, valid_session
        expect(assigns(:effleurage_option)).to be_a(EffleurageOption)
        expect(assigns(:effleurage_option)).to be_persisted
      end

      it "redirects to the created effleurage_option" do
        post :create, {:effleurage_option => valid_attributes}, valid_session
        expect(response).to redirect_to(EffleurageOption.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved effleurage_option as @effleurage_option" do
        post :create, {:effleurage_option => invalid_attributes}, valid_session
        expect(assigns(:effleurage_option)).to be_a_new(EffleurageOption)
      end

      it "re-renders the 'new' template" do
        post :create, {:effleurage_option => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested effleurage_option" do
        effleurage_option = EffleurageOption.create! valid_attributes
        put :update, {:id => effleurage_option.to_param, :effleurage_option => new_attributes}, valid_session
        effleurage_option.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested effleurage_option as @effleurage_option" do
        effleurage_option = EffleurageOption.create! valid_attributes
        put :update, {:id => effleurage_option.to_param, :effleurage_option => valid_attributes}, valid_session
        expect(assigns(:effleurage_option)).to eq(effleurage_option)
      end

      it "redirects to the effleurage_option" do
        effleurage_option = EffleurageOption.create! valid_attributes
        put :update, {:id => effleurage_option.to_param, :effleurage_option => valid_attributes}, valid_session
        expect(response).to redirect_to(effleurage_option)
      end
    end

    context "with invalid params" do
      it "assigns the effleurage_option as @effleurage_option" do
        effleurage_option = EffleurageOption.create! valid_attributes
        put :update, {:id => effleurage_option.to_param, :effleurage_option => invalid_attributes}, valid_session
        expect(assigns(:effleurage_option)).to eq(effleurage_option)
      end

      it "re-renders the 'edit' template" do
        effleurage_option = EffleurageOption.create! valid_attributes
        put :update, {:id => effleurage_option.to_param, :effleurage_option => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested effleurage_option" do
      effleurage_option = EffleurageOption.create! valid_attributes
      expect {
        delete :destroy, {:id => effleurage_option.to_param}, valid_session
      }.to change(EffleurageOption, :count).by(-1)
    end

    it "redirects to the effleurage_options list" do
      effleurage_option = EffleurageOption.create! valid_attributes
      delete :destroy, {:id => effleurage_option.to_param}, valid_session
      expect(response).to redirect_to(effleurage_options_url)
    end
  end

end
